
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Notification
 * 
 */
export type Notification = Prisma.NotificationModel
/**
 * Model Feedback
 * 
 */
export type Feedback = Prisma.FeedbackModel
/**
 * Model Location
 * 
 */
export type Location = Prisma.LocationModel
/**
 * Model Sabaq
 * 
 */
export type Sabaq = Prisma.SabaqModel
/**
 * Model SabaqAdmin
 * 
 */
export type SabaqAdmin = Prisma.SabaqAdminModel
/**
 * Model Enrollment
 * 
 */
export type Enrollment = Prisma.EnrollmentModel
/**
 * Model Session
 * 
 */
export type Session = Prisma.SessionModel
/**
 * Model Attendance
 * 
 */
export type Attendance = Prisma.AttendanceModel
/**
 * Model Question
 * 
 */
export type Question = Prisma.QuestionModel
/**
 * Model QuestionVote
 * 
 */
export type QuestionVote = Prisma.QuestionVoteModel
/**
 * Model EmailLog
 * 
 */
export type EmailLog = Prisma.EmailLogModel
/**
 * Model SecurityLog
 * 
 */
export type SecurityLog = Prisma.SecurityLogModel
/**
 * Model AttendanceRequest
 * 
 */
export type AttendanceRequest = Prisma.AttendanceRequestModel
/**
 * Model AdminOTP
 * 
 */
export type AdminOTP = Prisma.AdminOTPModel
/**
 * Model AppConfig
 * 
 */
export type AppConfig = Prisma.AppConfigModel
