
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Notification'
export type * from './models/Feedback'
export type * from './models/Location'
export type * from './models/Sabaq'
export type * from './models/SabaqAdmin'
export type * from './models/Enrollment'
export type * from './models/Session'
export type * from './models/Attendance'
export type * from './models/Question'
export type * from './models/QuestionVote'
export type * from './models/EmailLog'
export type * from './models/SecurityLog'
export type * from './models/AttendanceRequest'
export type * from './models/AdminOTP'
export type * from './models/AppConfig'
export type * from './commonInputTypes'