
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Notification: 'Notification',
  Feedback: 'Feedback',
  Location: 'Location',
  Sabaq: 'Sabaq',
  SabaqAdmin: 'SabaqAdmin',
  Enrollment: 'Enrollment',
  Session: 'Session',
  Attendance: 'Attendance',
  Question: 'Question',
  QuestionVote: 'QuestionVote',
  EmailLog: 'EmailLog',
  SecurityLog: 'SecurityLog',
  AttendanceRequest: 'AttendanceRequest',
  AdminOTP: 'AdminOTP',
  AppConfig: 'AppConfig'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  itsNumber: 'itsNumber',
  name: 'name',
  gender: 'gender',
  email: 'email',
  phone: 'phone',
  role: 'role',
  password: 'password',
  profileImage: 'profileImage',
  qrCode: 'qrCode',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  managedSabaqsCount: 'managedSabaqsCount',
  questionsCount: 'questionsCount',
  attendedCount: 'attendedCount',
  enrollmentCount: 'enrollmentCount',
  lateCount: 'lateCount'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  data: 'data',
  isRead: 'isRead',
  createdAt: 'createdAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const FeedbackScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  userId: 'userId',
  rating: 'rating',
  comment: 'comment',
  createdAt: 'createdAt'
} as const

export type FeedbackScalarFieldEnum = (typeof FeedbackScalarFieldEnum)[keyof typeof FeedbackScalarFieldEnum]


export const LocationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  address: 'address',
  latitude: 'latitude',
  longitude: 'longitude',
  radiusMeters: 'radiusMeters',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  sabaqsCount: 'sabaqsCount'
} as const

export type LocationScalarFieldEnum = (typeof LocationScalarFieldEnum)[keyof typeof LocationScalarFieldEnum]


export const SabaqScalarFieldEnum = {
  id: 'id',
  name: 'name',
  kitaab: 'kitaab',
  level: 'level',
  description: 'description',
  criteria: 'criteria',
  enrollmentStartsAt: 'enrollmentStartsAt',
  enrollmentEndsAt: 'enrollmentEndsAt',
  whatsappGroupLink: 'whatsappGroupLink',
  allowLocationAttendance: 'allowLocationAttendance',
  locationId: 'locationId',
  janabId: 'janabId',
  isActive: 'isActive',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  activeSessionId: 'activeSessionId',
  conductedSessionsCount: 'conductedSessionsCount',
  enrollmentCount: 'enrollmentCount'
} as const

export type SabaqScalarFieldEnum = (typeof SabaqScalarFieldEnum)[keyof typeof SabaqScalarFieldEnum]


export const SabaqAdminScalarFieldEnum = {
  id: 'id',
  sabaqId: 'sabaqId',
  userId: 'userId',
  assignedAt: 'assignedAt'
} as const

export type SabaqAdminScalarFieldEnum = (typeof SabaqAdminScalarFieldEnum)[keyof typeof SabaqAdminScalarFieldEnum]


export const EnrollmentScalarFieldEnum = {
  id: 'id',
  sabaqId: 'sabaqId',
  userId: 'userId',
  status: 'status',
  requestedAt: 'requestedAt',
  approvedAt: 'approvedAt',
  approvedBy: 'approvedBy',
  rejectedAt: 'rejectedAt',
  rejectedBy: 'rejectedBy',
  rejectionReason: 'rejectionReason'
} as const

export type EnrollmentScalarFieldEnum = (typeof EnrollmentScalarFieldEnum)[keyof typeof EnrollmentScalarFieldEnum]


export const SessionScalarFieldEnum = {
  id: 'id',
  sabaqId: 'sabaqId',
  scheduledAt: 'scheduledAt',
  cutoffTime: 'cutoffTime',
  startedAt: 'startedAt',
  endedAt: 'endedAt',
  isActive: 'isActive',
  isSynced: 'isSynced',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  attendanceCount: 'attendanceCount',
  questionsCount: 'questionsCount'
} as const

export type SessionScalarFieldEnum = (typeof SessionScalarFieldEnum)[keyof typeof SessionScalarFieldEnum]


export const AttendanceScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  userId: 'userId',
  itsNumber: 'itsNumber',
  markedAt: 'markedAt',
  markedBy: 'markedBy',
  method: 'method',
  latitude: 'latitude',
  longitude: 'longitude',
  distanceMeters: 'distanceMeters',
  isLate: 'isLate',
  minutesLate: 'minutesLate',
  isVerified: 'isVerified'
} as const

export type AttendanceScalarFieldEnum = (typeof AttendanceScalarFieldEnum)[keyof typeof AttendanceScalarFieldEnum]


export const QuestionScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  sabaqId: 'sabaqId',
  userId: 'userId',
  question: 'question',
  upvotes: 'upvotes',
  isAnswered: 'isAnswered',
  answer: 'answer',
  answeredBy: 'answeredBy',
  answeredAt: 'answeredAt',
  createdAt: 'createdAt'
} as const

export type QuestionScalarFieldEnum = (typeof QuestionScalarFieldEnum)[keyof typeof QuestionScalarFieldEnum]


export const QuestionVoteScalarFieldEnum = {
  id: 'id',
  questionId: 'questionId',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type QuestionVoteScalarFieldEnum = (typeof QuestionVoteScalarFieldEnum)[keyof typeof QuestionVoteScalarFieldEnum]


export const EmailLogScalarFieldEnum = {
  id: 'id',
  to: 'to',
  subject: 'subject',
  template: 'template',
  status: 'status',
  error: 'error',
  sentAt: 'sentAt',
  createdAt: 'createdAt'
} as const

export type EmailLogScalarFieldEnum = (typeof EmailLogScalarFieldEnum)[keyof typeof EmailLogScalarFieldEnum]


export const SecurityLogScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  action: 'action',
  resource: 'resource',
  details: 'details',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  createdAt: 'createdAt'
} as const

export type SecurityLogScalarFieldEnum = (typeof SecurityLogScalarFieldEnum)[keyof typeof SecurityLogScalarFieldEnum]


export const AttendanceRequestScalarFieldEnum = {
  id: 'id',
  sessionId: 'sessionId',
  userId: 'userId',
  itsNumber: 'itsNumber',
  requestedAt: 'requestedAt',
  status: 'status'
} as const

export type AttendanceRequestScalarFieldEnum = (typeof AttendanceRequestScalarFieldEnum)[keyof typeof AttendanceRequestScalarFieldEnum]


export const AdminOTPScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  code: 'code',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt'
} as const

export type AdminOTPScalarFieldEnum = (typeof AdminOTPScalarFieldEnum)[keyof typeof AdminOTPScalarFieldEnum]


export const AppConfigScalarFieldEnum = {
  id: 'id',
  isAdminUp: 'isAdminUp',
  isPostApiUp: 'isPostApiUp',
  isGetApiUp: 'isGetApiUp',
  isUnderMaintenance: 'isUnderMaintenance',
  version: 'version',
  overallStatus: 'overallStatus',
  downReason: 'downReason',
  updatedAt: 'updatedAt'
} as const

export type AppConfigScalarFieldEnum = (typeof AppConfigScalarFieldEnum)[keyof typeof AppConfigScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

