
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AdminOTP` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AdminOTP
 * 
 */
export type AdminOTPModel = runtime.Types.Result.DefaultSelection<Prisma.$AdminOTPPayload>

export type AggregateAdminOTP = {
  _count: AdminOTPCountAggregateOutputType | null
  _min: AdminOTPMinAggregateOutputType | null
  _max: AdminOTPMaxAggregateOutputType | null
}

export type AdminOTPMinAggregateOutputType = {
  id: string | null
  userId: string | null
  code: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type AdminOTPMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  code: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type AdminOTPCountAggregateOutputType = {
  id: number
  userId: number
  code: number
  expiresAt: number
  createdAt: number
  _all: number
}


export type AdminOTPMinAggregateInputType = {
  id?: true
  userId?: true
  code?: true
  expiresAt?: true
  createdAt?: true
}

export type AdminOTPMaxAggregateInputType = {
  id?: true
  userId?: true
  code?: true
  expiresAt?: true
  createdAt?: true
}

export type AdminOTPCountAggregateInputType = {
  id?: true
  userId?: true
  code?: true
  expiresAt?: true
  createdAt?: true
  _all?: true
}

export type AdminOTPAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdminOTP to aggregate.
   */
  where?: Prisma.AdminOTPWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdminOTPS to fetch.
   */
  orderBy?: Prisma.AdminOTPOrderByWithRelationInput | Prisma.AdminOTPOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AdminOTPWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdminOTPS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdminOTPS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AdminOTPS
  **/
  _count?: true | AdminOTPCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AdminOTPMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AdminOTPMaxAggregateInputType
}

export type GetAdminOTPAggregateType<T extends AdminOTPAggregateArgs> = {
      [P in keyof T & keyof AggregateAdminOTP]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAdminOTP[P]>
    : Prisma.GetScalarType<T[P], AggregateAdminOTP[P]>
}




export type AdminOTPGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AdminOTPWhereInput
  orderBy?: Prisma.AdminOTPOrderByWithAggregationInput | Prisma.AdminOTPOrderByWithAggregationInput[]
  by: Prisma.AdminOTPScalarFieldEnum[] | Prisma.AdminOTPScalarFieldEnum
  having?: Prisma.AdminOTPScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AdminOTPCountAggregateInputType | true
  _min?: AdminOTPMinAggregateInputType
  _max?: AdminOTPMaxAggregateInputType
}

export type AdminOTPGroupByOutputType = {
  id: string
  userId: string
  code: string
  expiresAt: Date
  createdAt: Date
  _count: AdminOTPCountAggregateOutputType | null
  _min: AdminOTPMinAggregateOutputType | null
  _max: AdminOTPMaxAggregateOutputType | null
}

type GetAdminOTPGroupByPayload<T extends AdminOTPGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AdminOTPGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AdminOTPGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AdminOTPGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AdminOTPGroupByOutputType[P]>
      }
    >
  >



export type AdminOTPWhereInput = {
  AND?: Prisma.AdminOTPWhereInput | Prisma.AdminOTPWhereInput[]
  OR?: Prisma.AdminOTPWhereInput[]
  NOT?: Prisma.AdminOTPWhereInput | Prisma.AdminOTPWhereInput[]
  id?: Prisma.StringFilter<"AdminOTP"> | string
  userId?: Prisma.StringFilter<"AdminOTP"> | string
  code?: Prisma.StringFilter<"AdminOTP"> | string
  expiresAt?: Prisma.DateTimeFilter<"AdminOTP"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"AdminOTP"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type AdminOTPOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type AdminOTPWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AdminOTPWhereInput | Prisma.AdminOTPWhereInput[]
  OR?: Prisma.AdminOTPWhereInput[]
  NOT?: Prisma.AdminOTPWhereInput | Prisma.AdminOTPWhereInput[]
  userId?: Prisma.StringFilter<"AdminOTP"> | string
  code?: Prisma.StringFilter<"AdminOTP"> | string
  expiresAt?: Prisma.DateTimeFilter<"AdminOTP"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"AdminOTP"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type AdminOTPOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AdminOTPCountOrderByAggregateInput
  _max?: Prisma.AdminOTPMaxOrderByAggregateInput
  _min?: Prisma.AdminOTPMinOrderByAggregateInput
}

export type AdminOTPScalarWhereWithAggregatesInput = {
  AND?: Prisma.AdminOTPScalarWhereWithAggregatesInput | Prisma.AdminOTPScalarWhereWithAggregatesInput[]
  OR?: Prisma.AdminOTPScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AdminOTPScalarWhereWithAggregatesInput | Prisma.AdminOTPScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AdminOTP"> | string
  userId?: Prisma.StringWithAggregatesFilter<"AdminOTP"> | string
  code?: Prisma.StringWithAggregatesFilter<"AdminOTP"> | string
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"AdminOTP"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AdminOTP"> | Date | string
}

export type AdminOTPCreateInput = {
  id?: string
  code: string
  expiresAt: Date | string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAdminOTPInput
}

export type AdminOTPUncheckedCreateInput = {
  id?: string
  userId: string
  code: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type AdminOTPUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAdminOTPNestedInput
}

export type AdminOTPUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdminOTPCreateManyInput = {
  id?: string
  userId: string
  code: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type AdminOTPUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdminOTPUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdminOTPListRelationFilter = {
  every?: Prisma.AdminOTPWhereInput
  some?: Prisma.AdminOTPWhereInput
  none?: Prisma.AdminOTPWhereInput
}

export type AdminOTPOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AdminOTPCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AdminOTPMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AdminOTPMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  code?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AdminOTPCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AdminOTPCreateWithoutUserInput, Prisma.AdminOTPUncheckedCreateWithoutUserInput> | Prisma.AdminOTPCreateWithoutUserInput[] | Prisma.AdminOTPUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AdminOTPCreateOrConnectWithoutUserInput | Prisma.AdminOTPCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AdminOTPCreateManyUserInputEnvelope
  connect?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
}

export type AdminOTPUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AdminOTPCreateWithoutUserInput, Prisma.AdminOTPUncheckedCreateWithoutUserInput> | Prisma.AdminOTPCreateWithoutUserInput[] | Prisma.AdminOTPUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AdminOTPCreateOrConnectWithoutUserInput | Prisma.AdminOTPCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AdminOTPCreateManyUserInputEnvelope
  connect?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
}

export type AdminOTPUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AdminOTPCreateWithoutUserInput, Prisma.AdminOTPUncheckedCreateWithoutUserInput> | Prisma.AdminOTPCreateWithoutUserInput[] | Prisma.AdminOTPUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AdminOTPCreateOrConnectWithoutUserInput | Prisma.AdminOTPCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AdminOTPUpsertWithWhereUniqueWithoutUserInput | Prisma.AdminOTPUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AdminOTPCreateManyUserInputEnvelope
  set?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
  disconnect?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
  delete?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
  connect?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
  update?: Prisma.AdminOTPUpdateWithWhereUniqueWithoutUserInput | Prisma.AdminOTPUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AdminOTPUpdateManyWithWhereWithoutUserInput | Prisma.AdminOTPUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AdminOTPScalarWhereInput | Prisma.AdminOTPScalarWhereInput[]
}

export type AdminOTPUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AdminOTPCreateWithoutUserInput, Prisma.AdminOTPUncheckedCreateWithoutUserInput> | Prisma.AdminOTPCreateWithoutUserInput[] | Prisma.AdminOTPUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AdminOTPCreateOrConnectWithoutUserInput | Prisma.AdminOTPCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AdminOTPUpsertWithWhereUniqueWithoutUserInput | Prisma.AdminOTPUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AdminOTPCreateManyUserInputEnvelope
  set?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
  disconnect?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
  delete?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
  connect?: Prisma.AdminOTPWhereUniqueInput | Prisma.AdminOTPWhereUniqueInput[]
  update?: Prisma.AdminOTPUpdateWithWhereUniqueWithoutUserInput | Prisma.AdminOTPUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AdminOTPUpdateManyWithWhereWithoutUserInput | Prisma.AdminOTPUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AdminOTPScalarWhereInput | Prisma.AdminOTPScalarWhereInput[]
}

export type AdminOTPCreateWithoutUserInput = {
  id?: string
  code: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type AdminOTPUncheckedCreateWithoutUserInput = {
  id?: string
  code: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type AdminOTPCreateOrConnectWithoutUserInput = {
  where: Prisma.AdminOTPWhereUniqueInput
  create: Prisma.XOR<Prisma.AdminOTPCreateWithoutUserInput, Prisma.AdminOTPUncheckedCreateWithoutUserInput>
}

export type AdminOTPCreateManyUserInputEnvelope = {
  data: Prisma.AdminOTPCreateManyUserInput | Prisma.AdminOTPCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AdminOTPUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AdminOTPWhereUniqueInput
  update: Prisma.XOR<Prisma.AdminOTPUpdateWithoutUserInput, Prisma.AdminOTPUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AdminOTPCreateWithoutUserInput, Prisma.AdminOTPUncheckedCreateWithoutUserInput>
}

export type AdminOTPUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AdminOTPWhereUniqueInput
  data: Prisma.XOR<Prisma.AdminOTPUpdateWithoutUserInput, Prisma.AdminOTPUncheckedUpdateWithoutUserInput>
}

export type AdminOTPUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AdminOTPScalarWhereInput
  data: Prisma.XOR<Prisma.AdminOTPUpdateManyMutationInput, Prisma.AdminOTPUncheckedUpdateManyWithoutUserInput>
}

export type AdminOTPScalarWhereInput = {
  AND?: Prisma.AdminOTPScalarWhereInput | Prisma.AdminOTPScalarWhereInput[]
  OR?: Prisma.AdminOTPScalarWhereInput[]
  NOT?: Prisma.AdminOTPScalarWhereInput | Prisma.AdminOTPScalarWhereInput[]
  id?: Prisma.StringFilter<"AdminOTP"> | string
  userId?: Prisma.StringFilter<"AdminOTP"> | string
  code?: Prisma.StringFilter<"AdminOTP"> | string
  expiresAt?: Prisma.DateTimeFilter<"AdminOTP"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"AdminOTP"> | Date | string
}

export type AdminOTPCreateManyUserInput = {
  id?: string
  code: string
  expiresAt: Date | string
  createdAt?: Date | string
}

export type AdminOTPUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdminOTPUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AdminOTPUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  code?: Prisma.StringFieldUpdateOperationsInput | string
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AdminOTPSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  code?: boolean
  expiresAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["adminOTP"]>

export type AdminOTPSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  code?: boolean
  expiresAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["adminOTP"]>

export type AdminOTPSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  code?: boolean
  expiresAt?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["adminOTP"]>

export type AdminOTPSelectScalar = {
  id?: boolean
  userId?: boolean
  code?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}

export type AdminOTPOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "code" | "expiresAt" | "createdAt", ExtArgs["result"]["adminOTP"]>
export type AdminOTPInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AdminOTPIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AdminOTPIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AdminOTPPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AdminOTP"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    code: string
    expiresAt: Date
    createdAt: Date
  }, ExtArgs["result"]["adminOTP"]>
  composites: {}
}

export type AdminOTPGetPayload<S extends boolean | null | undefined | AdminOTPDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload, S>

export type AdminOTPCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AdminOTPFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AdminOTPCountAggregateInputType | true
  }

export interface AdminOTPDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AdminOTP'], meta: { name: 'AdminOTP' } }
  /**
   * Find zero or one AdminOTP that matches the filter.
   * @param {AdminOTPFindUniqueArgs} args - Arguments to find a AdminOTP
   * @example
   * // Get one AdminOTP
   * const adminOTP = await prisma.adminOTP.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AdminOTPFindUniqueArgs>(args: Prisma.SelectSubset<T, AdminOTPFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AdminOTPClient<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AdminOTP that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AdminOTPFindUniqueOrThrowArgs} args - Arguments to find a AdminOTP
   * @example
   * // Get one AdminOTP
   * const adminOTP = await prisma.adminOTP.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AdminOTPFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AdminOTPFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdminOTPClient<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdminOTP that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminOTPFindFirstArgs} args - Arguments to find a AdminOTP
   * @example
   * // Get one AdminOTP
   * const adminOTP = await prisma.adminOTP.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AdminOTPFindFirstArgs>(args?: Prisma.SelectSubset<T, AdminOTPFindFirstArgs<ExtArgs>>): Prisma.Prisma__AdminOTPClient<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AdminOTP that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminOTPFindFirstOrThrowArgs} args - Arguments to find a AdminOTP
   * @example
   * // Get one AdminOTP
   * const adminOTP = await prisma.adminOTP.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AdminOTPFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AdminOTPFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AdminOTPClient<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AdminOTPS that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminOTPFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AdminOTPS
   * const adminOTPS = await prisma.adminOTP.findMany()
   * 
   * // Get first 10 AdminOTPS
   * const adminOTPS = await prisma.adminOTP.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const adminOTPWithIdOnly = await prisma.adminOTP.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AdminOTPFindManyArgs>(args?: Prisma.SelectSubset<T, AdminOTPFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AdminOTP.
   * @param {AdminOTPCreateArgs} args - Arguments to create a AdminOTP.
   * @example
   * // Create one AdminOTP
   * const AdminOTP = await prisma.adminOTP.create({
   *   data: {
   *     // ... data to create a AdminOTP
   *   }
   * })
   * 
   */
  create<T extends AdminOTPCreateArgs>(args: Prisma.SelectSubset<T, AdminOTPCreateArgs<ExtArgs>>): Prisma.Prisma__AdminOTPClient<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AdminOTPS.
   * @param {AdminOTPCreateManyArgs} args - Arguments to create many AdminOTPS.
   * @example
   * // Create many AdminOTPS
   * const adminOTP = await prisma.adminOTP.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AdminOTPCreateManyArgs>(args?: Prisma.SelectSubset<T, AdminOTPCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AdminOTPS and returns the data saved in the database.
   * @param {AdminOTPCreateManyAndReturnArgs} args - Arguments to create many AdminOTPS.
   * @example
   * // Create many AdminOTPS
   * const adminOTP = await prisma.adminOTP.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AdminOTPS and only return the `id`
   * const adminOTPWithIdOnly = await prisma.adminOTP.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AdminOTPCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AdminOTPCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AdminOTP.
   * @param {AdminOTPDeleteArgs} args - Arguments to delete one AdminOTP.
   * @example
   * // Delete one AdminOTP
   * const AdminOTP = await prisma.adminOTP.delete({
   *   where: {
   *     // ... filter to delete one AdminOTP
   *   }
   * })
   * 
   */
  delete<T extends AdminOTPDeleteArgs>(args: Prisma.SelectSubset<T, AdminOTPDeleteArgs<ExtArgs>>): Prisma.Prisma__AdminOTPClient<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AdminOTP.
   * @param {AdminOTPUpdateArgs} args - Arguments to update one AdminOTP.
   * @example
   * // Update one AdminOTP
   * const adminOTP = await prisma.adminOTP.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AdminOTPUpdateArgs>(args: Prisma.SelectSubset<T, AdminOTPUpdateArgs<ExtArgs>>): Prisma.Prisma__AdminOTPClient<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AdminOTPS.
   * @param {AdminOTPDeleteManyArgs} args - Arguments to filter AdminOTPS to delete.
   * @example
   * // Delete a few AdminOTPS
   * const { count } = await prisma.adminOTP.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AdminOTPDeleteManyArgs>(args?: Prisma.SelectSubset<T, AdminOTPDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AdminOTPS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminOTPUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AdminOTPS
   * const adminOTP = await prisma.adminOTP.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AdminOTPUpdateManyArgs>(args: Prisma.SelectSubset<T, AdminOTPUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AdminOTPS and returns the data updated in the database.
   * @param {AdminOTPUpdateManyAndReturnArgs} args - Arguments to update many AdminOTPS.
   * @example
   * // Update many AdminOTPS
   * const adminOTP = await prisma.adminOTP.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AdminOTPS and only return the `id`
   * const adminOTPWithIdOnly = await prisma.adminOTP.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AdminOTPUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AdminOTPUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AdminOTP.
   * @param {AdminOTPUpsertArgs} args - Arguments to update or create a AdminOTP.
   * @example
   * // Update or create a AdminOTP
   * const adminOTP = await prisma.adminOTP.upsert({
   *   create: {
   *     // ... data to create a AdminOTP
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AdminOTP we want to update
   *   }
   * })
   */
  upsert<T extends AdminOTPUpsertArgs>(args: Prisma.SelectSubset<T, AdminOTPUpsertArgs<ExtArgs>>): Prisma.Prisma__AdminOTPClient<runtime.Types.Result.GetResult<Prisma.$AdminOTPPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AdminOTPS.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminOTPCountArgs} args - Arguments to filter AdminOTPS to count.
   * @example
   * // Count the number of AdminOTPS
   * const count = await prisma.adminOTP.count({
   *   where: {
   *     // ... the filter for the AdminOTPS we want to count
   *   }
   * })
  **/
  count<T extends AdminOTPCountArgs>(
    args?: Prisma.Subset<T, AdminOTPCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AdminOTPCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AdminOTP.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminOTPAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AdminOTPAggregateArgs>(args: Prisma.Subset<T, AdminOTPAggregateArgs>): Prisma.PrismaPromise<GetAdminOTPAggregateType<T>>

  /**
   * Group by AdminOTP.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AdminOTPGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AdminOTPGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AdminOTPGroupByArgs['orderBy'] }
      : { orderBy?: AdminOTPGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AdminOTPGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAdminOTPGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AdminOTP model
 */
readonly fields: AdminOTPFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AdminOTP.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AdminOTPClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AdminOTP model
 */
export interface AdminOTPFieldRefs {
  readonly id: Prisma.FieldRef<"AdminOTP", 'String'>
  readonly userId: Prisma.FieldRef<"AdminOTP", 'String'>
  readonly code: Prisma.FieldRef<"AdminOTP", 'String'>
  readonly expiresAt: Prisma.FieldRef<"AdminOTP", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"AdminOTP", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AdminOTP findUnique
 */
export type AdminOTPFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
  /**
   * Filter, which AdminOTP to fetch.
   */
  where: Prisma.AdminOTPWhereUniqueInput
}

/**
 * AdminOTP findUniqueOrThrow
 */
export type AdminOTPFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
  /**
   * Filter, which AdminOTP to fetch.
   */
  where: Prisma.AdminOTPWhereUniqueInput
}

/**
 * AdminOTP findFirst
 */
export type AdminOTPFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
  /**
   * Filter, which AdminOTP to fetch.
   */
  where?: Prisma.AdminOTPWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdminOTPS to fetch.
   */
  orderBy?: Prisma.AdminOTPOrderByWithRelationInput | Prisma.AdminOTPOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdminOTPS.
   */
  cursor?: Prisma.AdminOTPWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdminOTPS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdminOTPS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdminOTPS.
   */
  distinct?: Prisma.AdminOTPScalarFieldEnum | Prisma.AdminOTPScalarFieldEnum[]
}

/**
 * AdminOTP findFirstOrThrow
 */
export type AdminOTPFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
  /**
   * Filter, which AdminOTP to fetch.
   */
  where?: Prisma.AdminOTPWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdminOTPS to fetch.
   */
  orderBy?: Prisma.AdminOTPOrderByWithRelationInput | Prisma.AdminOTPOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AdminOTPS.
   */
  cursor?: Prisma.AdminOTPWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdminOTPS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdminOTPS.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AdminOTPS.
   */
  distinct?: Prisma.AdminOTPScalarFieldEnum | Prisma.AdminOTPScalarFieldEnum[]
}

/**
 * AdminOTP findMany
 */
export type AdminOTPFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
  /**
   * Filter, which AdminOTPS to fetch.
   */
  where?: Prisma.AdminOTPWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AdminOTPS to fetch.
   */
  orderBy?: Prisma.AdminOTPOrderByWithRelationInput | Prisma.AdminOTPOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AdminOTPS.
   */
  cursor?: Prisma.AdminOTPWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AdminOTPS from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AdminOTPS.
   */
  skip?: number
  distinct?: Prisma.AdminOTPScalarFieldEnum | Prisma.AdminOTPScalarFieldEnum[]
}

/**
 * AdminOTP create
 */
export type AdminOTPCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
  /**
   * The data needed to create a AdminOTP.
   */
  data: Prisma.XOR<Prisma.AdminOTPCreateInput, Prisma.AdminOTPUncheckedCreateInput>
}

/**
 * AdminOTP createMany
 */
export type AdminOTPCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AdminOTPS.
   */
  data: Prisma.AdminOTPCreateManyInput | Prisma.AdminOTPCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AdminOTP createManyAndReturn
 */
export type AdminOTPCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * The data used to create many AdminOTPS.
   */
  data: Prisma.AdminOTPCreateManyInput | Prisma.AdminOTPCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AdminOTP update
 */
export type AdminOTPUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
  /**
   * The data needed to update a AdminOTP.
   */
  data: Prisma.XOR<Prisma.AdminOTPUpdateInput, Prisma.AdminOTPUncheckedUpdateInput>
  /**
   * Choose, which AdminOTP to update.
   */
  where: Prisma.AdminOTPWhereUniqueInput
}

/**
 * AdminOTP updateMany
 */
export type AdminOTPUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AdminOTPS.
   */
  data: Prisma.XOR<Prisma.AdminOTPUpdateManyMutationInput, Prisma.AdminOTPUncheckedUpdateManyInput>
  /**
   * Filter which AdminOTPS to update
   */
  where?: Prisma.AdminOTPWhereInput
  /**
   * Limit how many AdminOTPS to update.
   */
  limit?: number
}

/**
 * AdminOTP updateManyAndReturn
 */
export type AdminOTPUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * The data used to update AdminOTPS.
   */
  data: Prisma.XOR<Prisma.AdminOTPUpdateManyMutationInput, Prisma.AdminOTPUncheckedUpdateManyInput>
  /**
   * Filter which AdminOTPS to update
   */
  where?: Prisma.AdminOTPWhereInput
  /**
   * Limit how many AdminOTPS to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AdminOTP upsert
 */
export type AdminOTPUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
  /**
   * The filter to search for the AdminOTP to update in case it exists.
   */
  where: Prisma.AdminOTPWhereUniqueInput
  /**
   * In case the AdminOTP found by the `where` argument doesn't exist, create a new AdminOTP with this data.
   */
  create: Prisma.XOR<Prisma.AdminOTPCreateInput, Prisma.AdminOTPUncheckedCreateInput>
  /**
   * In case the AdminOTP was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AdminOTPUpdateInput, Prisma.AdminOTPUncheckedUpdateInput>
}

/**
 * AdminOTP delete
 */
export type AdminOTPDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
  /**
   * Filter which AdminOTP to delete.
   */
  where: Prisma.AdminOTPWhereUniqueInput
}

/**
 * AdminOTP deleteMany
 */
export type AdminOTPDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AdminOTPS to delete
   */
  where?: Prisma.AdminOTPWhereInput
  /**
   * Limit how many AdminOTPS to delete.
   */
  limit?: number
}

/**
 * AdminOTP without action
 */
export type AdminOTPDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AdminOTP
   */
  select?: Prisma.AdminOTPSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AdminOTP
   */
  omit?: Prisma.AdminOTPOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AdminOTPInclude<ExtArgs> | null
}
