
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `QuestionVote` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model QuestionVote
 * 
 */
export type QuestionVoteModel = runtime.Types.Result.DefaultSelection<Prisma.$QuestionVotePayload>

export type AggregateQuestionVote = {
  _count: QuestionVoteCountAggregateOutputType | null
  _min: QuestionVoteMinAggregateOutputType | null
  _max: QuestionVoteMaxAggregateOutputType | null
}

export type QuestionVoteMinAggregateOutputType = {
  id: string | null
  questionId: string | null
  userId: string | null
  createdAt: Date | null
}

export type QuestionVoteMaxAggregateOutputType = {
  id: string | null
  questionId: string | null
  userId: string | null
  createdAt: Date | null
}

export type QuestionVoteCountAggregateOutputType = {
  id: number
  questionId: number
  userId: number
  createdAt: number
  _all: number
}


export type QuestionVoteMinAggregateInputType = {
  id?: true
  questionId?: true
  userId?: true
  createdAt?: true
}

export type QuestionVoteMaxAggregateInputType = {
  id?: true
  questionId?: true
  userId?: true
  createdAt?: true
}

export type QuestionVoteCountAggregateInputType = {
  id?: true
  questionId?: true
  userId?: true
  createdAt?: true
  _all?: true
}

export type QuestionVoteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionVote to aggregate.
   */
  where?: Prisma.QuestionVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionVotes to fetch.
   */
  orderBy?: Prisma.QuestionVoteOrderByWithRelationInput | Prisma.QuestionVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.QuestionVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned QuestionVotes
  **/
  _count?: true | QuestionVoteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: QuestionVoteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: QuestionVoteMaxAggregateInputType
}

export type GetQuestionVoteAggregateType<T extends QuestionVoteAggregateArgs> = {
      [P in keyof T & keyof AggregateQuestionVote]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQuestionVote[P]>
    : Prisma.GetScalarType<T[P], AggregateQuestionVote[P]>
}




export type QuestionVoteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionVoteWhereInput
  orderBy?: Prisma.QuestionVoteOrderByWithAggregationInput | Prisma.QuestionVoteOrderByWithAggregationInput[]
  by: Prisma.QuestionVoteScalarFieldEnum[] | Prisma.QuestionVoteScalarFieldEnum
  having?: Prisma.QuestionVoteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: QuestionVoteCountAggregateInputType | true
  _min?: QuestionVoteMinAggregateInputType
  _max?: QuestionVoteMaxAggregateInputType
}

export type QuestionVoteGroupByOutputType = {
  id: string
  questionId: string
  userId: string
  createdAt: Date
  _count: QuestionVoteCountAggregateOutputType | null
  _min: QuestionVoteMinAggregateOutputType | null
  _max: QuestionVoteMaxAggregateOutputType | null
}

type GetQuestionVoteGroupByPayload<T extends QuestionVoteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<QuestionVoteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof QuestionVoteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], QuestionVoteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], QuestionVoteGroupByOutputType[P]>
      }
    >
  >



export type QuestionVoteWhereInput = {
  AND?: Prisma.QuestionVoteWhereInput | Prisma.QuestionVoteWhereInput[]
  OR?: Prisma.QuestionVoteWhereInput[]
  NOT?: Prisma.QuestionVoteWhereInput | Prisma.QuestionVoteWhereInput[]
  id?: Prisma.StringFilter<"QuestionVote"> | string
  questionId?: Prisma.StringFilter<"QuestionVote"> | string
  userId?: Prisma.StringFilter<"QuestionVote"> | string
  createdAt?: Prisma.DateTimeFilter<"QuestionVote"> | Date | string
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type QuestionVoteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  question?: Prisma.QuestionOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type QuestionVoteWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  questionId_userId?: Prisma.QuestionVoteQuestionIdUserIdCompoundUniqueInput
  AND?: Prisma.QuestionVoteWhereInput | Prisma.QuestionVoteWhereInput[]
  OR?: Prisma.QuestionVoteWhereInput[]
  NOT?: Prisma.QuestionVoteWhereInput | Prisma.QuestionVoteWhereInput[]
  questionId?: Prisma.StringFilter<"QuestionVote"> | string
  userId?: Prisma.StringFilter<"QuestionVote"> | string
  createdAt?: Prisma.DateTimeFilter<"QuestionVote"> | Date | string
  question?: Prisma.XOR<Prisma.QuestionScalarRelationFilter, Prisma.QuestionWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "questionId_userId">

export type QuestionVoteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.QuestionVoteCountOrderByAggregateInput
  _max?: Prisma.QuestionVoteMaxOrderByAggregateInput
  _min?: Prisma.QuestionVoteMinOrderByAggregateInput
}

export type QuestionVoteScalarWhereWithAggregatesInput = {
  AND?: Prisma.QuestionVoteScalarWhereWithAggregatesInput | Prisma.QuestionVoteScalarWhereWithAggregatesInput[]
  OR?: Prisma.QuestionVoteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.QuestionVoteScalarWhereWithAggregatesInput | Prisma.QuestionVoteScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"QuestionVote"> | string
  questionId?: Prisma.StringWithAggregatesFilter<"QuestionVote"> | string
  userId?: Prisma.StringWithAggregatesFilter<"QuestionVote"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"QuestionVote"> | Date | string
}

export type QuestionVoteCreateInput = {
  id?: string
  createdAt?: Date | string
  question: Prisma.QuestionCreateNestedOneWithoutVotesInput
  user: Prisma.UserCreateNestedOneWithoutVotesInput
}

export type QuestionVoteUncheckedCreateInput = {
  id?: string
  questionId: string
  userId: string
  createdAt?: Date | string
}

export type QuestionVoteUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question?: Prisma.QuestionUpdateOneRequiredWithoutVotesNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutVotesNestedInput
}

export type QuestionVoteUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionVoteCreateManyInput = {
  id?: string
  questionId: string
  userId: string
  createdAt?: Date | string
}

export type QuestionVoteUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionVoteUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionVoteListRelationFilter = {
  every?: Prisma.QuestionVoteWhereInput
  some?: Prisma.QuestionVoteWhereInput
  none?: Prisma.QuestionVoteWhereInput
}

export type QuestionVoteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type QuestionVoteQuestionIdUserIdCompoundUniqueInput = {
  questionId: string
  userId: string
}

export type QuestionVoteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuestionVoteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuestionVoteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  questionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type QuestionVoteCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QuestionVoteCreateWithoutUserInput, Prisma.QuestionVoteUncheckedCreateWithoutUserInput> | Prisma.QuestionVoteCreateWithoutUserInput[] | Prisma.QuestionVoteUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuestionVoteCreateOrConnectWithoutUserInput | Prisma.QuestionVoteCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.QuestionVoteCreateManyUserInputEnvelope
  connect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
}

export type QuestionVoteUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.QuestionVoteCreateWithoutUserInput, Prisma.QuestionVoteUncheckedCreateWithoutUserInput> | Prisma.QuestionVoteCreateWithoutUserInput[] | Prisma.QuestionVoteUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuestionVoteCreateOrConnectWithoutUserInput | Prisma.QuestionVoteCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.QuestionVoteCreateManyUserInputEnvelope
  connect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
}

export type QuestionVoteUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionVoteCreateWithoutUserInput, Prisma.QuestionVoteUncheckedCreateWithoutUserInput> | Prisma.QuestionVoteCreateWithoutUserInput[] | Prisma.QuestionVoteUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuestionVoteCreateOrConnectWithoutUserInput | Prisma.QuestionVoteCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.QuestionVoteUpsertWithWhereUniqueWithoutUserInput | Prisma.QuestionVoteUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.QuestionVoteCreateManyUserInputEnvelope
  set?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  disconnect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  delete?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  connect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  update?: Prisma.QuestionVoteUpdateWithWhereUniqueWithoutUserInput | Prisma.QuestionVoteUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.QuestionVoteUpdateManyWithWhereWithoutUserInput | Prisma.QuestionVoteUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.QuestionVoteScalarWhereInput | Prisma.QuestionVoteScalarWhereInput[]
}

export type QuestionVoteUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionVoteCreateWithoutUserInput, Prisma.QuestionVoteUncheckedCreateWithoutUserInput> | Prisma.QuestionVoteCreateWithoutUserInput[] | Prisma.QuestionVoteUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.QuestionVoteCreateOrConnectWithoutUserInput | Prisma.QuestionVoteCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.QuestionVoteUpsertWithWhereUniqueWithoutUserInput | Prisma.QuestionVoteUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.QuestionVoteCreateManyUserInputEnvelope
  set?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  disconnect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  delete?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  connect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  update?: Prisma.QuestionVoteUpdateWithWhereUniqueWithoutUserInput | Prisma.QuestionVoteUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.QuestionVoteUpdateManyWithWhereWithoutUserInput | Prisma.QuestionVoteUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.QuestionVoteScalarWhereInput | Prisma.QuestionVoteScalarWhereInput[]
}

export type QuestionVoteCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuestionVoteCreateWithoutQuestionInput, Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput> | Prisma.QuestionVoteCreateWithoutQuestionInput[] | Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuestionVoteCreateOrConnectWithoutQuestionInput | Prisma.QuestionVoteCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuestionVoteCreateManyQuestionInputEnvelope
  connect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
}

export type QuestionVoteUncheckedCreateNestedManyWithoutQuestionInput = {
  create?: Prisma.XOR<Prisma.QuestionVoteCreateWithoutQuestionInput, Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput> | Prisma.QuestionVoteCreateWithoutQuestionInput[] | Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuestionVoteCreateOrConnectWithoutQuestionInput | Prisma.QuestionVoteCreateOrConnectWithoutQuestionInput[]
  createMany?: Prisma.QuestionVoteCreateManyQuestionInputEnvelope
  connect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
}

export type QuestionVoteUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionVoteCreateWithoutQuestionInput, Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput> | Prisma.QuestionVoteCreateWithoutQuestionInput[] | Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuestionVoteCreateOrConnectWithoutQuestionInput | Prisma.QuestionVoteCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuestionVoteUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuestionVoteUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuestionVoteCreateManyQuestionInputEnvelope
  set?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  disconnect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  delete?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  connect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  update?: Prisma.QuestionVoteUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuestionVoteUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuestionVoteUpdateManyWithWhereWithoutQuestionInput | Prisma.QuestionVoteUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuestionVoteScalarWhereInput | Prisma.QuestionVoteScalarWhereInput[]
}

export type QuestionVoteUncheckedUpdateManyWithoutQuestionNestedInput = {
  create?: Prisma.XOR<Prisma.QuestionVoteCreateWithoutQuestionInput, Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput> | Prisma.QuestionVoteCreateWithoutQuestionInput[] | Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput[]
  connectOrCreate?: Prisma.QuestionVoteCreateOrConnectWithoutQuestionInput | Prisma.QuestionVoteCreateOrConnectWithoutQuestionInput[]
  upsert?: Prisma.QuestionVoteUpsertWithWhereUniqueWithoutQuestionInput | Prisma.QuestionVoteUpsertWithWhereUniqueWithoutQuestionInput[]
  createMany?: Prisma.QuestionVoteCreateManyQuestionInputEnvelope
  set?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  disconnect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  delete?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  connect?: Prisma.QuestionVoteWhereUniqueInput | Prisma.QuestionVoteWhereUniqueInput[]
  update?: Prisma.QuestionVoteUpdateWithWhereUniqueWithoutQuestionInput | Prisma.QuestionVoteUpdateWithWhereUniqueWithoutQuestionInput[]
  updateMany?: Prisma.QuestionVoteUpdateManyWithWhereWithoutQuestionInput | Prisma.QuestionVoteUpdateManyWithWhereWithoutQuestionInput[]
  deleteMany?: Prisma.QuestionVoteScalarWhereInput | Prisma.QuestionVoteScalarWhereInput[]
}

export type QuestionVoteCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  question: Prisma.QuestionCreateNestedOneWithoutVotesInput
}

export type QuestionVoteUncheckedCreateWithoutUserInput = {
  id?: string
  questionId: string
  createdAt?: Date | string
}

export type QuestionVoteCreateOrConnectWithoutUserInput = {
  where: Prisma.QuestionVoteWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionVoteCreateWithoutUserInput, Prisma.QuestionVoteUncheckedCreateWithoutUserInput>
}

export type QuestionVoteCreateManyUserInputEnvelope = {
  data: Prisma.QuestionVoteCreateManyUserInput | Prisma.QuestionVoteCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type QuestionVoteUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.QuestionVoteWhereUniqueInput
  update: Prisma.XOR<Prisma.QuestionVoteUpdateWithoutUserInput, Prisma.QuestionVoteUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.QuestionVoteCreateWithoutUserInput, Prisma.QuestionVoteUncheckedCreateWithoutUserInput>
}

export type QuestionVoteUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.QuestionVoteWhereUniqueInput
  data: Prisma.XOR<Prisma.QuestionVoteUpdateWithoutUserInput, Prisma.QuestionVoteUncheckedUpdateWithoutUserInput>
}

export type QuestionVoteUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.QuestionVoteScalarWhereInput
  data: Prisma.XOR<Prisma.QuestionVoteUpdateManyMutationInput, Prisma.QuestionVoteUncheckedUpdateManyWithoutUserInput>
}

export type QuestionVoteScalarWhereInput = {
  AND?: Prisma.QuestionVoteScalarWhereInput | Prisma.QuestionVoteScalarWhereInput[]
  OR?: Prisma.QuestionVoteScalarWhereInput[]
  NOT?: Prisma.QuestionVoteScalarWhereInput | Prisma.QuestionVoteScalarWhereInput[]
  id?: Prisma.StringFilter<"QuestionVote"> | string
  questionId?: Prisma.StringFilter<"QuestionVote"> | string
  userId?: Prisma.StringFilter<"QuestionVote"> | string
  createdAt?: Prisma.DateTimeFilter<"QuestionVote"> | Date | string
}

export type QuestionVoteCreateWithoutQuestionInput = {
  id?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutVotesInput
}

export type QuestionVoteUncheckedCreateWithoutQuestionInput = {
  id?: string
  userId: string
  createdAt?: Date | string
}

export type QuestionVoteCreateOrConnectWithoutQuestionInput = {
  where: Prisma.QuestionVoteWhereUniqueInput
  create: Prisma.XOR<Prisma.QuestionVoteCreateWithoutQuestionInput, Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput>
}

export type QuestionVoteCreateManyQuestionInputEnvelope = {
  data: Prisma.QuestionVoteCreateManyQuestionInput | Prisma.QuestionVoteCreateManyQuestionInput[]
  skipDuplicates?: boolean
}

export type QuestionVoteUpsertWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuestionVoteWhereUniqueInput
  update: Prisma.XOR<Prisma.QuestionVoteUpdateWithoutQuestionInput, Prisma.QuestionVoteUncheckedUpdateWithoutQuestionInput>
  create: Prisma.XOR<Prisma.QuestionVoteCreateWithoutQuestionInput, Prisma.QuestionVoteUncheckedCreateWithoutQuestionInput>
}

export type QuestionVoteUpdateWithWhereUniqueWithoutQuestionInput = {
  where: Prisma.QuestionVoteWhereUniqueInput
  data: Prisma.XOR<Prisma.QuestionVoteUpdateWithoutQuestionInput, Prisma.QuestionVoteUncheckedUpdateWithoutQuestionInput>
}

export type QuestionVoteUpdateManyWithWhereWithoutQuestionInput = {
  where: Prisma.QuestionVoteScalarWhereInput
  data: Prisma.XOR<Prisma.QuestionVoteUpdateManyMutationInput, Prisma.QuestionVoteUncheckedUpdateManyWithoutQuestionInput>
}

export type QuestionVoteCreateManyUserInput = {
  id?: string
  questionId: string
  createdAt?: Date | string
}

export type QuestionVoteUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  question?: Prisma.QuestionUpdateOneRequiredWithoutVotesNestedInput
}

export type QuestionVoteUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionVoteUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  questionId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionVoteCreateManyQuestionInput = {
  id?: string
  userId: string
  createdAt?: Date | string
}

export type QuestionVoteUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutVotesNestedInput
}

export type QuestionVoteUncheckedUpdateWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type QuestionVoteUncheckedUpdateManyWithoutQuestionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type QuestionVoteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionId?: boolean
  userId?: boolean
  createdAt?: boolean
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionVote"]>

export type QuestionVoteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionId?: boolean
  userId?: boolean
  createdAt?: boolean
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionVote"]>

export type QuestionVoteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  questionId?: boolean
  userId?: boolean
  createdAt?: boolean
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["questionVote"]>

export type QuestionVoteSelectScalar = {
  id?: boolean
  questionId?: boolean
  userId?: boolean
  createdAt?: boolean
}

export type QuestionVoteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "questionId" | "userId" | "createdAt", ExtArgs["result"]["questionVote"]>
export type QuestionVoteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type QuestionVoteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type QuestionVoteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  question?: boolean | Prisma.QuestionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $QuestionVotePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "QuestionVote"
  objects: {
    question: Prisma.$QuestionPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    questionId: string
    userId: string
    createdAt: Date
  }, ExtArgs["result"]["questionVote"]>
  composites: {}
}

export type QuestionVoteGetPayload<S extends boolean | null | undefined | QuestionVoteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload, S>

export type QuestionVoteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<QuestionVoteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: QuestionVoteCountAggregateInputType | true
  }

export interface QuestionVoteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['QuestionVote'], meta: { name: 'QuestionVote' } }
  /**
   * Find zero or one QuestionVote that matches the filter.
   * @param {QuestionVoteFindUniqueArgs} args - Arguments to find a QuestionVote
   * @example
   * // Get one QuestionVote
   * const questionVote = await prisma.questionVote.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends QuestionVoteFindUniqueArgs>(args: Prisma.SelectSubset<T, QuestionVoteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__QuestionVoteClient<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one QuestionVote that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {QuestionVoteFindUniqueOrThrowArgs} args - Arguments to find a QuestionVote
   * @example
   * // Get one QuestionVote
   * const questionVote = await prisma.questionVote.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends QuestionVoteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, QuestionVoteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionVoteClient<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionVote that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionVoteFindFirstArgs} args - Arguments to find a QuestionVote
   * @example
   * // Get one QuestionVote
   * const questionVote = await prisma.questionVote.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends QuestionVoteFindFirstArgs>(args?: Prisma.SelectSubset<T, QuestionVoteFindFirstArgs<ExtArgs>>): Prisma.Prisma__QuestionVoteClient<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first QuestionVote that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionVoteFindFirstOrThrowArgs} args - Arguments to find a QuestionVote
   * @example
   * // Get one QuestionVote
   * const questionVote = await prisma.questionVote.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends QuestionVoteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, QuestionVoteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__QuestionVoteClient<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more QuestionVotes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionVoteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all QuestionVotes
   * const questionVotes = await prisma.questionVote.findMany()
   * 
   * // Get first 10 QuestionVotes
   * const questionVotes = await prisma.questionVote.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const questionVoteWithIdOnly = await prisma.questionVote.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends QuestionVoteFindManyArgs>(args?: Prisma.SelectSubset<T, QuestionVoteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a QuestionVote.
   * @param {QuestionVoteCreateArgs} args - Arguments to create a QuestionVote.
   * @example
   * // Create one QuestionVote
   * const QuestionVote = await prisma.questionVote.create({
   *   data: {
   *     // ... data to create a QuestionVote
   *   }
   * })
   * 
   */
  create<T extends QuestionVoteCreateArgs>(args: Prisma.SelectSubset<T, QuestionVoteCreateArgs<ExtArgs>>): Prisma.Prisma__QuestionVoteClient<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many QuestionVotes.
   * @param {QuestionVoteCreateManyArgs} args - Arguments to create many QuestionVotes.
   * @example
   * // Create many QuestionVotes
   * const questionVote = await prisma.questionVote.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends QuestionVoteCreateManyArgs>(args?: Prisma.SelectSubset<T, QuestionVoteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many QuestionVotes and returns the data saved in the database.
   * @param {QuestionVoteCreateManyAndReturnArgs} args - Arguments to create many QuestionVotes.
   * @example
   * // Create many QuestionVotes
   * const questionVote = await prisma.questionVote.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many QuestionVotes and only return the `id`
   * const questionVoteWithIdOnly = await prisma.questionVote.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends QuestionVoteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, QuestionVoteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a QuestionVote.
   * @param {QuestionVoteDeleteArgs} args - Arguments to delete one QuestionVote.
   * @example
   * // Delete one QuestionVote
   * const QuestionVote = await prisma.questionVote.delete({
   *   where: {
   *     // ... filter to delete one QuestionVote
   *   }
   * })
   * 
   */
  delete<T extends QuestionVoteDeleteArgs>(args: Prisma.SelectSubset<T, QuestionVoteDeleteArgs<ExtArgs>>): Prisma.Prisma__QuestionVoteClient<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one QuestionVote.
   * @param {QuestionVoteUpdateArgs} args - Arguments to update one QuestionVote.
   * @example
   * // Update one QuestionVote
   * const questionVote = await prisma.questionVote.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends QuestionVoteUpdateArgs>(args: Prisma.SelectSubset<T, QuestionVoteUpdateArgs<ExtArgs>>): Prisma.Prisma__QuestionVoteClient<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more QuestionVotes.
   * @param {QuestionVoteDeleteManyArgs} args - Arguments to filter QuestionVotes to delete.
   * @example
   * // Delete a few QuestionVotes
   * const { count } = await prisma.questionVote.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends QuestionVoteDeleteManyArgs>(args?: Prisma.SelectSubset<T, QuestionVoteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionVotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionVoteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many QuestionVotes
   * const questionVote = await prisma.questionVote.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends QuestionVoteUpdateManyArgs>(args: Prisma.SelectSubset<T, QuestionVoteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more QuestionVotes and returns the data updated in the database.
   * @param {QuestionVoteUpdateManyAndReturnArgs} args - Arguments to update many QuestionVotes.
   * @example
   * // Update many QuestionVotes
   * const questionVote = await prisma.questionVote.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more QuestionVotes and only return the `id`
   * const questionVoteWithIdOnly = await prisma.questionVote.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends QuestionVoteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, QuestionVoteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one QuestionVote.
   * @param {QuestionVoteUpsertArgs} args - Arguments to update or create a QuestionVote.
   * @example
   * // Update or create a QuestionVote
   * const questionVote = await prisma.questionVote.upsert({
   *   create: {
   *     // ... data to create a QuestionVote
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the QuestionVote we want to update
   *   }
   * })
   */
  upsert<T extends QuestionVoteUpsertArgs>(args: Prisma.SelectSubset<T, QuestionVoteUpsertArgs<ExtArgs>>): Prisma.Prisma__QuestionVoteClient<runtime.Types.Result.GetResult<Prisma.$QuestionVotePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of QuestionVotes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionVoteCountArgs} args - Arguments to filter QuestionVotes to count.
   * @example
   * // Count the number of QuestionVotes
   * const count = await prisma.questionVote.count({
   *   where: {
   *     // ... the filter for the QuestionVotes we want to count
   *   }
   * })
  **/
  count<T extends QuestionVoteCountArgs>(
    args?: Prisma.Subset<T, QuestionVoteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], QuestionVoteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a QuestionVote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionVoteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends QuestionVoteAggregateArgs>(args: Prisma.Subset<T, QuestionVoteAggregateArgs>): Prisma.PrismaPromise<GetQuestionVoteAggregateType<T>>

  /**
   * Group by QuestionVote.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {QuestionVoteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends QuestionVoteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: QuestionVoteGroupByArgs['orderBy'] }
      : { orderBy?: QuestionVoteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, QuestionVoteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetQuestionVoteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the QuestionVote model
 */
readonly fields: QuestionVoteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for QuestionVote.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__QuestionVoteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  question<T extends Prisma.QuestionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.QuestionDefaultArgs<ExtArgs>>): Prisma.Prisma__QuestionClient<runtime.Types.Result.GetResult<Prisma.$QuestionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the QuestionVote model
 */
export interface QuestionVoteFieldRefs {
  readonly id: Prisma.FieldRef<"QuestionVote", 'String'>
  readonly questionId: Prisma.FieldRef<"QuestionVote", 'String'>
  readonly userId: Prisma.FieldRef<"QuestionVote", 'String'>
  readonly createdAt: Prisma.FieldRef<"QuestionVote", 'DateTime'>
}
    

// Custom InputTypes
/**
 * QuestionVote findUnique
 */
export type QuestionVoteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which QuestionVote to fetch.
   */
  where: Prisma.QuestionVoteWhereUniqueInput
}

/**
 * QuestionVote findUniqueOrThrow
 */
export type QuestionVoteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which QuestionVote to fetch.
   */
  where: Prisma.QuestionVoteWhereUniqueInput
}

/**
 * QuestionVote findFirst
 */
export type QuestionVoteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which QuestionVote to fetch.
   */
  where?: Prisma.QuestionVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionVotes to fetch.
   */
  orderBy?: Prisma.QuestionVoteOrderByWithRelationInput | Prisma.QuestionVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionVotes.
   */
  cursor?: Prisma.QuestionVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionVotes.
   */
  distinct?: Prisma.QuestionVoteScalarFieldEnum | Prisma.QuestionVoteScalarFieldEnum[]
}

/**
 * QuestionVote findFirstOrThrow
 */
export type QuestionVoteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which QuestionVote to fetch.
   */
  where?: Prisma.QuestionVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionVotes to fetch.
   */
  orderBy?: Prisma.QuestionVoteOrderByWithRelationInput | Prisma.QuestionVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for QuestionVotes.
   */
  cursor?: Prisma.QuestionVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionVotes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of QuestionVotes.
   */
  distinct?: Prisma.QuestionVoteScalarFieldEnum | Prisma.QuestionVoteScalarFieldEnum[]
}

/**
 * QuestionVote findMany
 */
export type QuestionVoteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
  /**
   * Filter, which QuestionVotes to fetch.
   */
  where?: Prisma.QuestionVoteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of QuestionVotes to fetch.
   */
  orderBy?: Prisma.QuestionVoteOrderByWithRelationInput | Prisma.QuestionVoteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing QuestionVotes.
   */
  cursor?: Prisma.QuestionVoteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` QuestionVotes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` QuestionVotes.
   */
  skip?: number
  distinct?: Prisma.QuestionVoteScalarFieldEnum | Prisma.QuestionVoteScalarFieldEnum[]
}

/**
 * QuestionVote create
 */
export type QuestionVoteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
  /**
   * The data needed to create a QuestionVote.
   */
  data: Prisma.XOR<Prisma.QuestionVoteCreateInput, Prisma.QuestionVoteUncheckedCreateInput>
}

/**
 * QuestionVote createMany
 */
export type QuestionVoteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many QuestionVotes.
   */
  data: Prisma.QuestionVoteCreateManyInput | Prisma.QuestionVoteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * QuestionVote createManyAndReturn
 */
export type QuestionVoteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * The data used to create many QuestionVotes.
   */
  data: Prisma.QuestionVoteCreateManyInput | Prisma.QuestionVoteCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionVote update
 */
export type QuestionVoteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
  /**
   * The data needed to update a QuestionVote.
   */
  data: Prisma.XOR<Prisma.QuestionVoteUpdateInput, Prisma.QuestionVoteUncheckedUpdateInput>
  /**
   * Choose, which QuestionVote to update.
   */
  where: Prisma.QuestionVoteWhereUniqueInput
}

/**
 * QuestionVote updateMany
 */
export type QuestionVoteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update QuestionVotes.
   */
  data: Prisma.XOR<Prisma.QuestionVoteUpdateManyMutationInput, Prisma.QuestionVoteUncheckedUpdateManyInput>
  /**
   * Filter which QuestionVotes to update
   */
  where?: Prisma.QuestionVoteWhereInput
  /**
   * Limit how many QuestionVotes to update.
   */
  limit?: number
}

/**
 * QuestionVote updateManyAndReturn
 */
export type QuestionVoteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * The data used to update QuestionVotes.
   */
  data: Prisma.XOR<Prisma.QuestionVoteUpdateManyMutationInput, Prisma.QuestionVoteUncheckedUpdateManyInput>
  /**
   * Filter which QuestionVotes to update
   */
  where?: Prisma.QuestionVoteWhereInput
  /**
   * Limit how many QuestionVotes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * QuestionVote upsert
 */
export type QuestionVoteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
  /**
   * The filter to search for the QuestionVote to update in case it exists.
   */
  where: Prisma.QuestionVoteWhereUniqueInput
  /**
   * In case the QuestionVote found by the `where` argument doesn't exist, create a new QuestionVote with this data.
   */
  create: Prisma.XOR<Prisma.QuestionVoteCreateInput, Prisma.QuestionVoteUncheckedCreateInput>
  /**
   * In case the QuestionVote was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.QuestionVoteUpdateInput, Prisma.QuestionVoteUncheckedUpdateInput>
}

/**
 * QuestionVote delete
 */
export type QuestionVoteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
  /**
   * Filter which QuestionVote to delete.
   */
  where: Prisma.QuestionVoteWhereUniqueInput
}

/**
 * QuestionVote deleteMany
 */
export type QuestionVoteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which QuestionVotes to delete
   */
  where?: Prisma.QuestionVoteWhereInput
  /**
   * Limit how many QuestionVotes to delete.
   */
  limit?: number
}

/**
 * QuestionVote without action
 */
export type QuestionVoteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the QuestionVote
   */
  select?: Prisma.QuestionVoteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the QuestionVote
   */
  omit?: Prisma.QuestionVoteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionVoteInclude<ExtArgs> | null
}
