
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SabaqAdmin` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SabaqAdmin
 * 
 */
export type SabaqAdminModel = runtime.Types.Result.DefaultSelection<Prisma.$SabaqAdminPayload>

export type AggregateSabaqAdmin = {
  _count: SabaqAdminCountAggregateOutputType | null
  _min: SabaqAdminMinAggregateOutputType | null
  _max: SabaqAdminMaxAggregateOutputType | null
}

export type SabaqAdminMinAggregateOutputType = {
  id: string | null
  sabaqId: string | null
  userId: string | null
  assignedAt: Date | null
}

export type SabaqAdminMaxAggregateOutputType = {
  id: string | null
  sabaqId: string | null
  userId: string | null
  assignedAt: Date | null
}

export type SabaqAdminCountAggregateOutputType = {
  id: number
  sabaqId: number
  userId: number
  assignedAt: number
  _all: number
}


export type SabaqAdminMinAggregateInputType = {
  id?: true
  sabaqId?: true
  userId?: true
  assignedAt?: true
}

export type SabaqAdminMaxAggregateInputType = {
  id?: true
  sabaqId?: true
  userId?: true
  assignedAt?: true
}

export type SabaqAdminCountAggregateInputType = {
  id?: true
  sabaqId?: true
  userId?: true
  assignedAt?: true
  _all?: true
}

export type SabaqAdminAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SabaqAdmin to aggregate.
   */
  where?: Prisma.SabaqAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SabaqAdmins to fetch.
   */
  orderBy?: Prisma.SabaqAdminOrderByWithRelationInput | Prisma.SabaqAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SabaqAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SabaqAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SabaqAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SabaqAdmins
  **/
  _count?: true | SabaqAdminCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SabaqAdminMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SabaqAdminMaxAggregateInputType
}

export type GetSabaqAdminAggregateType<T extends SabaqAdminAggregateArgs> = {
      [P in keyof T & keyof AggregateSabaqAdmin]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSabaqAdmin[P]>
    : Prisma.GetScalarType<T[P], AggregateSabaqAdmin[P]>
}




export type SabaqAdminGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SabaqAdminWhereInput
  orderBy?: Prisma.SabaqAdminOrderByWithAggregationInput | Prisma.SabaqAdminOrderByWithAggregationInput[]
  by: Prisma.SabaqAdminScalarFieldEnum[] | Prisma.SabaqAdminScalarFieldEnum
  having?: Prisma.SabaqAdminScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SabaqAdminCountAggregateInputType | true
  _min?: SabaqAdminMinAggregateInputType
  _max?: SabaqAdminMaxAggregateInputType
}

export type SabaqAdminGroupByOutputType = {
  id: string
  sabaqId: string
  userId: string
  assignedAt: Date
  _count: SabaqAdminCountAggregateOutputType | null
  _min: SabaqAdminMinAggregateOutputType | null
  _max: SabaqAdminMaxAggregateOutputType | null
}

type GetSabaqAdminGroupByPayload<T extends SabaqAdminGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SabaqAdminGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SabaqAdminGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SabaqAdminGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SabaqAdminGroupByOutputType[P]>
      }
    >
  >



export type SabaqAdminWhereInput = {
  AND?: Prisma.SabaqAdminWhereInput | Prisma.SabaqAdminWhereInput[]
  OR?: Prisma.SabaqAdminWhereInput[]
  NOT?: Prisma.SabaqAdminWhereInput | Prisma.SabaqAdminWhereInput[]
  id?: Prisma.StringFilter<"SabaqAdmin"> | string
  sabaqId?: Prisma.StringFilter<"SabaqAdmin"> | string
  userId?: Prisma.StringFilter<"SabaqAdmin"> | string
  assignedAt?: Prisma.DateTimeFilter<"SabaqAdmin"> | Date | string
  sabaq?: Prisma.XOR<Prisma.SabaqScalarRelationFilter, Prisma.SabaqWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type SabaqAdminOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  sabaq?: Prisma.SabaqOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type SabaqAdminWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  sabaqId_userId?: Prisma.SabaqAdminSabaqIdUserIdCompoundUniqueInput
  AND?: Prisma.SabaqAdminWhereInput | Prisma.SabaqAdminWhereInput[]
  OR?: Prisma.SabaqAdminWhereInput[]
  NOT?: Prisma.SabaqAdminWhereInput | Prisma.SabaqAdminWhereInput[]
  sabaqId?: Prisma.StringFilter<"SabaqAdmin"> | string
  userId?: Prisma.StringFilter<"SabaqAdmin"> | string
  assignedAt?: Prisma.DateTimeFilter<"SabaqAdmin"> | Date | string
  sabaq?: Prisma.XOR<Prisma.SabaqScalarRelationFilter, Prisma.SabaqWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "sabaqId_userId">

export type SabaqAdminOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
  _count?: Prisma.SabaqAdminCountOrderByAggregateInput
  _max?: Prisma.SabaqAdminMaxOrderByAggregateInput
  _min?: Prisma.SabaqAdminMinOrderByAggregateInput
}

export type SabaqAdminScalarWhereWithAggregatesInput = {
  AND?: Prisma.SabaqAdminScalarWhereWithAggregatesInput | Prisma.SabaqAdminScalarWhereWithAggregatesInput[]
  OR?: Prisma.SabaqAdminScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SabaqAdminScalarWhereWithAggregatesInput | Prisma.SabaqAdminScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SabaqAdmin"> | string
  sabaqId?: Prisma.StringWithAggregatesFilter<"SabaqAdmin"> | string
  userId?: Prisma.StringWithAggregatesFilter<"SabaqAdmin"> | string
  assignedAt?: Prisma.DateTimeWithAggregatesFilter<"SabaqAdmin"> | Date | string
}

export type SabaqAdminCreateInput = {
  id?: string
  assignedAt?: Date | string
  sabaq: Prisma.SabaqCreateNestedOneWithoutAdminsInput
  user: Prisma.UserCreateNestedOneWithoutAssignedSabaqsInput
}

export type SabaqAdminUncheckedCreateInput = {
  id?: string
  sabaqId: string
  userId: string
  assignedAt?: Date | string
}

export type SabaqAdminUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sabaq?: Prisma.SabaqUpdateOneRequiredWithoutAdminsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutAssignedSabaqsNestedInput
}

export type SabaqAdminUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SabaqAdminCreateManyInput = {
  id?: string
  sabaqId: string
  userId: string
  assignedAt?: Date | string
}

export type SabaqAdminUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SabaqAdminUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SabaqAdminListRelationFilter = {
  every?: Prisma.SabaqAdminWhereInput
  some?: Prisma.SabaqAdminWhereInput
  none?: Prisma.SabaqAdminWhereInput
}

export type SabaqAdminOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SabaqAdminSabaqIdUserIdCompoundUniqueInput = {
  sabaqId: string
  userId: string
}

export type SabaqAdminCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
}

export type SabaqAdminMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
}

export type SabaqAdminMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  assignedAt?: Prisma.SortOrder
}

export type SabaqAdminCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SabaqAdminCreateWithoutUserInput, Prisma.SabaqAdminUncheckedCreateWithoutUserInput> | Prisma.SabaqAdminCreateWithoutUserInput[] | Prisma.SabaqAdminUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SabaqAdminCreateOrConnectWithoutUserInput | Prisma.SabaqAdminCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SabaqAdminCreateManyUserInputEnvelope
  connect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
}

export type SabaqAdminUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SabaqAdminCreateWithoutUserInput, Prisma.SabaqAdminUncheckedCreateWithoutUserInput> | Prisma.SabaqAdminCreateWithoutUserInput[] | Prisma.SabaqAdminUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SabaqAdminCreateOrConnectWithoutUserInput | Prisma.SabaqAdminCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SabaqAdminCreateManyUserInputEnvelope
  connect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
}

export type SabaqAdminUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SabaqAdminCreateWithoutUserInput, Prisma.SabaqAdminUncheckedCreateWithoutUserInput> | Prisma.SabaqAdminCreateWithoutUserInput[] | Prisma.SabaqAdminUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SabaqAdminCreateOrConnectWithoutUserInput | Prisma.SabaqAdminCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SabaqAdminUpsertWithWhereUniqueWithoutUserInput | Prisma.SabaqAdminUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SabaqAdminCreateManyUserInputEnvelope
  set?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  disconnect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  delete?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  connect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  update?: Prisma.SabaqAdminUpdateWithWhereUniqueWithoutUserInput | Prisma.SabaqAdminUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SabaqAdminUpdateManyWithWhereWithoutUserInput | Prisma.SabaqAdminUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SabaqAdminScalarWhereInput | Prisma.SabaqAdminScalarWhereInput[]
}

export type SabaqAdminUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SabaqAdminCreateWithoutUserInput, Prisma.SabaqAdminUncheckedCreateWithoutUserInput> | Prisma.SabaqAdminCreateWithoutUserInput[] | Prisma.SabaqAdminUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SabaqAdminCreateOrConnectWithoutUserInput | Prisma.SabaqAdminCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SabaqAdminUpsertWithWhereUniqueWithoutUserInput | Prisma.SabaqAdminUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SabaqAdminCreateManyUserInputEnvelope
  set?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  disconnect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  delete?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  connect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  update?: Prisma.SabaqAdminUpdateWithWhereUniqueWithoutUserInput | Prisma.SabaqAdminUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SabaqAdminUpdateManyWithWhereWithoutUserInput | Prisma.SabaqAdminUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SabaqAdminScalarWhereInput | Prisma.SabaqAdminScalarWhereInput[]
}

export type SabaqAdminCreateNestedManyWithoutSabaqInput = {
  create?: Prisma.XOR<Prisma.SabaqAdminCreateWithoutSabaqInput, Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput> | Prisma.SabaqAdminCreateWithoutSabaqInput[] | Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput[]
  connectOrCreate?: Prisma.SabaqAdminCreateOrConnectWithoutSabaqInput | Prisma.SabaqAdminCreateOrConnectWithoutSabaqInput[]
  createMany?: Prisma.SabaqAdminCreateManySabaqInputEnvelope
  connect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
}

export type SabaqAdminUncheckedCreateNestedManyWithoutSabaqInput = {
  create?: Prisma.XOR<Prisma.SabaqAdminCreateWithoutSabaqInput, Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput> | Prisma.SabaqAdminCreateWithoutSabaqInput[] | Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput[]
  connectOrCreate?: Prisma.SabaqAdminCreateOrConnectWithoutSabaqInput | Prisma.SabaqAdminCreateOrConnectWithoutSabaqInput[]
  createMany?: Prisma.SabaqAdminCreateManySabaqInputEnvelope
  connect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
}

export type SabaqAdminUpdateManyWithoutSabaqNestedInput = {
  create?: Prisma.XOR<Prisma.SabaqAdminCreateWithoutSabaqInput, Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput> | Prisma.SabaqAdminCreateWithoutSabaqInput[] | Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput[]
  connectOrCreate?: Prisma.SabaqAdminCreateOrConnectWithoutSabaqInput | Prisma.SabaqAdminCreateOrConnectWithoutSabaqInput[]
  upsert?: Prisma.SabaqAdminUpsertWithWhereUniqueWithoutSabaqInput | Prisma.SabaqAdminUpsertWithWhereUniqueWithoutSabaqInput[]
  createMany?: Prisma.SabaqAdminCreateManySabaqInputEnvelope
  set?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  disconnect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  delete?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  connect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  update?: Prisma.SabaqAdminUpdateWithWhereUniqueWithoutSabaqInput | Prisma.SabaqAdminUpdateWithWhereUniqueWithoutSabaqInput[]
  updateMany?: Prisma.SabaqAdminUpdateManyWithWhereWithoutSabaqInput | Prisma.SabaqAdminUpdateManyWithWhereWithoutSabaqInput[]
  deleteMany?: Prisma.SabaqAdminScalarWhereInput | Prisma.SabaqAdminScalarWhereInput[]
}

export type SabaqAdminUncheckedUpdateManyWithoutSabaqNestedInput = {
  create?: Prisma.XOR<Prisma.SabaqAdminCreateWithoutSabaqInput, Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput> | Prisma.SabaqAdminCreateWithoutSabaqInput[] | Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput[]
  connectOrCreate?: Prisma.SabaqAdminCreateOrConnectWithoutSabaqInput | Prisma.SabaqAdminCreateOrConnectWithoutSabaqInput[]
  upsert?: Prisma.SabaqAdminUpsertWithWhereUniqueWithoutSabaqInput | Prisma.SabaqAdminUpsertWithWhereUniqueWithoutSabaqInput[]
  createMany?: Prisma.SabaqAdminCreateManySabaqInputEnvelope
  set?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  disconnect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  delete?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  connect?: Prisma.SabaqAdminWhereUniqueInput | Prisma.SabaqAdminWhereUniqueInput[]
  update?: Prisma.SabaqAdminUpdateWithWhereUniqueWithoutSabaqInput | Prisma.SabaqAdminUpdateWithWhereUniqueWithoutSabaqInput[]
  updateMany?: Prisma.SabaqAdminUpdateManyWithWhereWithoutSabaqInput | Prisma.SabaqAdminUpdateManyWithWhereWithoutSabaqInput[]
  deleteMany?: Prisma.SabaqAdminScalarWhereInput | Prisma.SabaqAdminScalarWhereInput[]
}

export type SabaqAdminCreateWithoutUserInput = {
  id?: string
  assignedAt?: Date | string
  sabaq: Prisma.SabaqCreateNestedOneWithoutAdminsInput
}

export type SabaqAdminUncheckedCreateWithoutUserInput = {
  id?: string
  sabaqId: string
  assignedAt?: Date | string
}

export type SabaqAdminCreateOrConnectWithoutUserInput = {
  where: Prisma.SabaqAdminWhereUniqueInput
  create: Prisma.XOR<Prisma.SabaqAdminCreateWithoutUserInput, Prisma.SabaqAdminUncheckedCreateWithoutUserInput>
}

export type SabaqAdminCreateManyUserInputEnvelope = {
  data: Prisma.SabaqAdminCreateManyUserInput | Prisma.SabaqAdminCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type SabaqAdminUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SabaqAdminWhereUniqueInput
  update: Prisma.XOR<Prisma.SabaqAdminUpdateWithoutUserInput, Prisma.SabaqAdminUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SabaqAdminCreateWithoutUserInput, Prisma.SabaqAdminUncheckedCreateWithoutUserInput>
}

export type SabaqAdminUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SabaqAdminWhereUniqueInput
  data: Prisma.XOR<Prisma.SabaqAdminUpdateWithoutUserInput, Prisma.SabaqAdminUncheckedUpdateWithoutUserInput>
}

export type SabaqAdminUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SabaqAdminScalarWhereInput
  data: Prisma.XOR<Prisma.SabaqAdminUpdateManyMutationInput, Prisma.SabaqAdminUncheckedUpdateManyWithoutUserInput>
}

export type SabaqAdminScalarWhereInput = {
  AND?: Prisma.SabaqAdminScalarWhereInput | Prisma.SabaqAdminScalarWhereInput[]
  OR?: Prisma.SabaqAdminScalarWhereInput[]
  NOT?: Prisma.SabaqAdminScalarWhereInput | Prisma.SabaqAdminScalarWhereInput[]
  id?: Prisma.StringFilter<"SabaqAdmin"> | string
  sabaqId?: Prisma.StringFilter<"SabaqAdmin"> | string
  userId?: Prisma.StringFilter<"SabaqAdmin"> | string
  assignedAt?: Prisma.DateTimeFilter<"SabaqAdmin"> | Date | string
}

export type SabaqAdminCreateWithoutSabaqInput = {
  id?: string
  assignedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAssignedSabaqsInput
}

export type SabaqAdminUncheckedCreateWithoutSabaqInput = {
  id?: string
  userId: string
  assignedAt?: Date | string
}

export type SabaqAdminCreateOrConnectWithoutSabaqInput = {
  where: Prisma.SabaqAdminWhereUniqueInput
  create: Prisma.XOR<Prisma.SabaqAdminCreateWithoutSabaqInput, Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput>
}

export type SabaqAdminCreateManySabaqInputEnvelope = {
  data: Prisma.SabaqAdminCreateManySabaqInput | Prisma.SabaqAdminCreateManySabaqInput[]
  skipDuplicates?: boolean
}

export type SabaqAdminUpsertWithWhereUniqueWithoutSabaqInput = {
  where: Prisma.SabaqAdminWhereUniqueInput
  update: Prisma.XOR<Prisma.SabaqAdminUpdateWithoutSabaqInput, Prisma.SabaqAdminUncheckedUpdateWithoutSabaqInput>
  create: Prisma.XOR<Prisma.SabaqAdminCreateWithoutSabaqInput, Prisma.SabaqAdminUncheckedCreateWithoutSabaqInput>
}

export type SabaqAdminUpdateWithWhereUniqueWithoutSabaqInput = {
  where: Prisma.SabaqAdminWhereUniqueInput
  data: Prisma.XOR<Prisma.SabaqAdminUpdateWithoutSabaqInput, Prisma.SabaqAdminUncheckedUpdateWithoutSabaqInput>
}

export type SabaqAdminUpdateManyWithWhereWithoutSabaqInput = {
  where: Prisma.SabaqAdminScalarWhereInput
  data: Prisma.XOR<Prisma.SabaqAdminUpdateManyMutationInput, Prisma.SabaqAdminUncheckedUpdateManyWithoutSabaqInput>
}

export type SabaqAdminCreateManyUserInput = {
  id?: string
  sabaqId: string
  assignedAt?: Date | string
}

export type SabaqAdminUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sabaq?: Prisma.SabaqUpdateOneRequiredWithoutAdminsNestedInput
}

export type SabaqAdminUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SabaqAdminUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SabaqAdminCreateManySabaqInput = {
  id?: string
  userId: string
  assignedAt?: Date | string
}

export type SabaqAdminUpdateWithoutSabaqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAssignedSabaqsNestedInput
}

export type SabaqAdminUncheckedUpdateWithoutSabaqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SabaqAdminUncheckedUpdateManyWithoutSabaqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  assignedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SabaqAdminSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sabaqId?: boolean
  userId?: boolean
  assignedAt?: boolean
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sabaqAdmin"]>

export type SabaqAdminSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sabaqId?: boolean
  userId?: boolean
  assignedAt?: boolean
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sabaqAdmin"]>

export type SabaqAdminSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sabaqId?: boolean
  userId?: boolean
  assignedAt?: boolean
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sabaqAdmin"]>

export type SabaqAdminSelectScalar = {
  id?: boolean
  sabaqId?: boolean
  userId?: boolean
  assignedAt?: boolean
}

export type SabaqAdminOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sabaqId" | "userId" | "assignedAt", ExtArgs["result"]["sabaqAdmin"]>
export type SabaqAdminInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SabaqAdminIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type SabaqAdminIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $SabaqAdminPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SabaqAdmin"
  objects: {
    sabaq: Prisma.$SabaqPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sabaqId: string
    userId: string
    assignedAt: Date
  }, ExtArgs["result"]["sabaqAdmin"]>
  composites: {}
}

export type SabaqAdminGetPayload<S extends boolean | null | undefined | SabaqAdminDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload, S>

export type SabaqAdminCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SabaqAdminFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SabaqAdminCountAggregateInputType | true
  }

export interface SabaqAdminDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SabaqAdmin'], meta: { name: 'SabaqAdmin' } }
  /**
   * Find zero or one SabaqAdmin that matches the filter.
   * @param {SabaqAdminFindUniqueArgs} args - Arguments to find a SabaqAdmin
   * @example
   * // Get one SabaqAdmin
   * const sabaqAdmin = await prisma.sabaqAdmin.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SabaqAdminFindUniqueArgs>(args: Prisma.SelectSubset<T, SabaqAdminFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SabaqAdminClient<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SabaqAdmin that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SabaqAdminFindUniqueOrThrowArgs} args - Arguments to find a SabaqAdmin
   * @example
   * // Get one SabaqAdmin
   * const sabaqAdmin = await prisma.sabaqAdmin.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SabaqAdminFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SabaqAdminFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SabaqAdminClient<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SabaqAdmin that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SabaqAdminFindFirstArgs} args - Arguments to find a SabaqAdmin
   * @example
   * // Get one SabaqAdmin
   * const sabaqAdmin = await prisma.sabaqAdmin.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SabaqAdminFindFirstArgs>(args?: Prisma.SelectSubset<T, SabaqAdminFindFirstArgs<ExtArgs>>): Prisma.Prisma__SabaqAdminClient<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SabaqAdmin that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SabaqAdminFindFirstOrThrowArgs} args - Arguments to find a SabaqAdmin
   * @example
   * // Get one SabaqAdmin
   * const sabaqAdmin = await prisma.sabaqAdmin.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SabaqAdminFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SabaqAdminFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SabaqAdminClient<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SabaqAdmins that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SabaqAdminFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SabaqAdmins
   * const sabaqAdmins = await prisma.sabaqAdmin.findMany()
   * 
   * // Get first 10 SabaqAdmins
   * const sabaqAdmins = await prisma.sabaqAdmin.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sabaqAdminWithIdOnly = await prisma.sabaqAdmin.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SabaqAdminFindManyArgs>(args?: Prisma.SelectSubset<T, SabaqAdminFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SabaqAdmin.
   * @param {SabaqAdminCreateArgs} args - Arguments to create a SabaqAdmin.
   * @example
   * // Create one SabaqAdmin
   * const SabaqAdmin = await prisma.sabaqAdmin.create({
   *   data: {
   *     // ... data to create a SabaqAdmin
   *   }
   * })
   * 
   */
  create<T extends SabaqAdminCreateArgs>(args: Prisma.SelectSubset<T, SabaqAdminCreateArgs<ExtArgs>>): Prisma.Prisma__SabaqAdminClient<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SabaqAdmins.
   * @param {SabaqAdminCreateManyArgs} args - Arguments to create many SabaqAdmins.
   * @example
   * // Create many SabaqAdmins
   * const sabaqAdmin = await prisma.sabaqAdmin.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SabaqAdminCreateManyArgs>(args?: Prisma.SelectSubset<T, SabaqAdminCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SabaqAdmins and returns the data saved in the database.
   * @param {SabaqAdminCreateManyAndReturnArgs} args - Arguments to create many SabaqAdmins.
   * @example
   * // Create many SabaqAdmins
   * const sabaqAdmin = await prisma.sabaqAdmin.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SabaqAdmins and only return the `id`
   * const sabaqAdminWithIdOnly = await prisma.sabaqAdmin.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SabaqAdminCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SabaqAdminCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SabaqAdmin.
   * @param {SabaqAdminDeleteArgs} args - Arguments to delete one SabaqAdmin.
   * @example
   * // Delete one SabaqAdmin
   * const SabaqAdmin = await prisma.sabaqAdmin.delete({
   *   where: {
   *     // ... filter to delete one SabaqAdmin
   *   }
   * })
   * 
   */
  delete<T extends SabaqAdminDeleteArgs>(args: Prisma.SelectSubset<T, SabaqAdminDeleteArgs<ExtArgs>>): Prisma.Prisma__SabaqAdminClient<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SabaqAdmin.
   * @param {SabaqAdminUpdateArgs} args - Arguments to update one SabaqAdmin.
   * @example
   * // Update one SabaqAdmin
   * const sabaqAdmin = await prisma.sabaqAdmin.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SabaqAdminUpdateArgs>(args: Prisma.SelectSubset<T, SabaqAdminUpdateArgs<ExtArgs>>): Prisma.Prisma__SabaqAdminClient<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SabaqAdmins.
   * @param {SabaqAdminDeleteManyArgs} args - Arguments to filter SabaqAdmins to delete.
   * @example
   * // Delete a few SabaqAdmins
   * const { count } = await prisma.sabaqAdmin.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SabaqAdminDeleteManyArgs>(args?: Prisma.SelectSubset<T, SabaqAdminDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SabaqAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SabaqAdminUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SabaqAdmins
   * const sabaqAdmin = await prisma.sabaqAdmin.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SabaqAdminUpdateManyArgs>(args: Prisma.SelectSubset<T, SabaqAdminUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SabaqAdmins and returns the data updated in the database.
   * @param {SabaqAdminUpdateManyAndReturnArgs} args - Arguments to update many SabaqAdmins.
   * @example
   * // Update many SabaqAdmins
   * const sabaqAdmin = await prisma.sabaqAdmin.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SabaqAdmins and only return the `id`
   * const sabaqAdminWithIdOnly = await prisma.sabaqAdmin.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SabaqAdminUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SabaqAdminUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SabaqAdmin.
   * @param {SabaqAdminUpsertArgs} args - Arguments to update or create a SabaqAdmin.
   * @example
   * // Update or create a SabaqAdmin
   * const sabaqAdmin = await prisma.sabaqAdmin.upsert({
   *   create: {
   *     // ... data to create a SabaqAdmin
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SabaqAdmin we want to update
   *   }
   * })
   */
  upsert<T extends SabaqAdminUpsertArgs>(args: Prisma.SelectSubset<T, SabaqAdminUpsertArgs<ExtArgs>>): Prisma.Prisma__SabaqAdminClient<runtime.Types.Result.GetResult<Prisma.$SabaqAdminPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SabaqAdmins.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SabaqAdminCountArgs} args - Arguments to filter SabaqAdmins to count.
   * @example
   * // Count the number of SabaqAdmins
   * const count = await prisma.sabaqAdmin.count({
   *   where: {
   *     // ... the filter for the SabaqAdmins we want to count
   *   }
   * })
  **/
  count<T extends SabaqAdminCountArgs>(
    args?: Prisma.Subset<T, SabaqAdminCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SabaqAdminCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SabaqAdmin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SabaqAdminAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SabaqAdminAggregateArgs>(args: Prisma.Subset<T, SabaqAdminAggregateArgs>): Prisma.PrismaPromise<GetSabaqAdminAggregateType<T>>

  /**
   * Group by SabaqAdmin.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SabaqAdminGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SabaqAdminGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SabaqAdminGroupByArgs['orderBy'] }
      : { orderBy?: SabaqAdminGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SabaqAdminGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSabaqAdminGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SabaqAdmin model
 */
readonly fields: SabaqAdminFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SabaqAdmin.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SabaqAdminClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sabaq<T extends Prisma.SabaqDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SabaqDefaultArgs<ExtArgs>>): Prisma.Prisma__SabaqClient<runtime.Types.Result.GetResult<Prisma.$SabaqPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SabaqAdmin model
 */
export interface SabaqAdminFieldRefs {
  readonly id: Prisma.FieldRef<"SabaqAdmin", 'String'>
  readonly sabaqId: Prisma.FieldRef<"SabaqAdmin", 'String'>
  readonly userId: Prisma.FieldRef<"SabaqAdmin", 'String'>
  readonly assignedAt: Prisma.FieldRef<"SabaqAdmin", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SabaqAdmin findUnique
 */
export type SabaqAdminFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
  /**
   * Filter, which SabaqAdmin to fetch.
   */
  where: Prisma.SabaqAdminWhereUniqueInput
}

/**
 * SabaqAdmin findUniqueOrThrow
 */
export type SabaqAdminFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
  /**
   * Filter, which SabaqAdmin to fetch.
   */
  where: Prisma.SabaqAdminWhereUniqueInput
}

/**
 * SabaqAdmin findFirst
 */
export type SabaqAdminFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
  /**
   * Filter, which SabaqAdmin to fetch.
   */
  where?: Prisma.SabaqAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SabaqAdmins to fetch.
   */
  orderBy?: Prisma.SabaqAdminOrderByWithRelationInput | Prisma.SabaqAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SabaqAdmins.
   */
  cursor?: Prisma.SabaqAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SabaqAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SabaqAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SabaqAdmins.
   */
  distinct?: Prisma.SabaqAdminScalarFieldEnum | Prisma.SabaqAdminScalarFieldEnum[]
}

/**
 * SabaqAdmin findFirstOrThrow
 */
export type SabaqAdminFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
  /**
   * Filter, which SabaqAdmin to fetch.
   */
  where?: Prisma.SabaqAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SabaqAdmins to fetch.
   */
  orderBy?: Prisma.SabaqAdminOrderByWithRelationInput | Prisma.SabaqAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SabaqAdmins.
   */
  cursor?: Prisma.SabaqAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SabaqAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SabaqAdmins.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SabaqAdmins.
   */
  distinct?: Prisma.SabaqAdminScalarFieldEnum | Prisma.SabaqAdminScalarFieldEnum[]
}

/**
 * SabaqAdmin findMany
 */
export type SabaqAdminFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
  /**
   * Filter, which SabaqAdmins to fetch.
   */
  where?: Prisma.SabaqAdminWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SabaqAdmins to fetch.
   */
  orderBy?: Prisma.SabaqAdminOrderByWithRelationInput | Prisma.SabaqAdminOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SabaqAdmins.
   */
  cursor?: Prisma.SabaqAdminWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SabaqAdmins from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SabaqAdmins.
   */
  skip?: number
  distinct?: Prisma.SabaqAdminScalarFieldEnum | Prisma.SabaqAdminScalarFieldEnum[]
}

/**
 * SabaqAdmin create
 */
export type SabaqAdminCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
  /**
   * The data needed to create a SabaqAdmin.
   */
  data: Prisma.XOR<Prisma.SabaqAdminCreateInput, Prisma.SabaqAdminUncheckedCreateInput>
}

/**
 * SabaqAdmin createMany
 */
export type SabaqAdminCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SabaqAdmins.
   */
  data: Prisma.SabaqAdminCreateManyInput | Prisma.SabaqAdminCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SabaqAdmin createManyAndReturn
 */
export type SabaqAdminCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * The data used to create many SabaqAdmins.
   */
  data: Prisma.SabaqAdminCreateManyInput | Prisma.SabaqAdminCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SabaqAdmin update
 */
export type SabaqAdminUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
  /**
   * The data needed to update a SabaqAdmin.
   */
  data: Prisma.XOR<Prisma.SabaqAdminUpdateInput, Prisma.SabaqAdminUncheckedUpdateInput>
  /**
   * Choose, which SabaqAdmin to update.
   */
  where: Prisma.SabaqAdminWhereUniqueInput
}

/**
 * SabaqAdmin updateMany
 */
export type SabaqAdminUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SabaqAdmins.
   */
  data: Prisma.XOR<Prisma.SabaqAdminUpdateManyMutationInput, Prisma.SabaqAdminUncheckedUpdateManyInput>
  /**
   * Filter which SabaqAdmins to update
   */
  where?: Prisma.SabaqAdminWhereInput
  /**
   * Limit how many SabaqAdmins to update.
   */
  limit?: number
}

/**
 * SabaqAdmin updateManyAndReturn
 */
export type SabaqAdminUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * The data used to update SabaqAdmins.
   */
  data: Prisma.XOR<Prisma.SabaqAdminUpdateManyMutationInput, Prisma.SabaqAdminUncheckedUpdateManyInput>
  /**
   * Filter which SabaqAdmins to update
   */
  where?: Prisma.SabaqAdminWhereInput
  /**
   * Limit how many SabaqAdmins to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SabaqAdmin upsert
 */
export type SabaqAdminUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
  /**
   * The filter to search for the SabaqAdmin to update in case it exists.
   */
  where: Prisma.SabaqAdminWhereUniqueInput
  /**
   * In case the SabaqAdmin found by the `where` argument doesn't exist, create a new SabaqAdmin with this data.
   */
  create: Prisma.XOR<Prisma.SabaqAdminCreateInput, Prisma.SabaqAdminUncheckedCreateInput>
  /**
   * In case the SabaqAdmin was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SabaqAdminUpdateInput, Prisma.SabaqAdminUncheckedUpdateInput>
}

/**
 * SabaqAdmin delete
 */
export type SabaqAdminDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
  /**
   * Filter which SabaqAdmin to delete.
   */
  where: Prisma.SabaqAdminWhereUniqueInput
}

/**
 * SabaqAdmin deleteMany
 */
export type SabaqAdminDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SabaqAdmins to delete
   */
  where?: Prisma.SabaqAdminWhereInput
  /**
   * Limit how many SabaqAdmins to delete.
   */
  limit?: number
}

/**
 * SabaqAdmin without action
 */
export type SabaqAdminDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SabaqAdmin
   */
  select?: Prisma.SabaqAdminSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SabaqAdmin
   */
  omit?: Prisma.SabaqAdminOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqAdminInclude<ExtArgs> | null
}
