
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Session` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Session
 * 
 */
export type SessionModel = runtime.Types.Result.DefaultSelection<Prisma.$SessionPayload>

export type AggregateSession = {
  _count: SessionCountAggregateOutputType | null
  _avg: SessionAvgAggregateOutputType | null
  _sum: SessionSumAggregateOutputType | null
  _min: SessionMinAggregateOutputType | null
  _max: SessionMaxAggregateOutputType | null
}

export type SessionAvgAggregateOutputType = {
  attendanceCount: number | null
  questionsCount: number | null
}

export type SessionSumAggregateOutputType = {
  attendanceCount: number | null
  questionsCount: number | null
}

export type SessionMinAggregateOutputType = {
  id: string | null
  sabaqId: string | null
  scheduledAt: Date | null
  cutoffTime: Date | null
  startedAt: Date | null
  endedAt: Date | null
  isActive: boolean | null
  isSynced: boolean | null
  createdBy: string | null
  createdAt: Date | null
  attendanceCount: number | null
  questionsCount: number | null
}

export type SessionMaxAggregateOutputType = {
  id: string | null
  sabaqId: string | null
  scheduledAt: Date | null
  cutoffTime: Date | null
  startedAt: Date | null
  endedAt: Date | null
  isActive: boolean | null
  isSynced: boolean | null
  createdBy: string | null
  createdAt: Date | null
  attendanceCount: number | null
  questionsCount: number | null
}

export type SessionCountAggregateOutputType = {
  id: number
  sabaqId: number
  scheduledAt: number
  cutoffTime: number
  startedAt: number
  endedAt: number
  isActive: number
  isSynced: number
  createdBy: number
  createdAt: number
  attendanceCount: number
  questionsCount: number
  _all: number
}


export type SessionAvgAggregateInputType = {
  attendanceCount?: true
  questionsCount?: true
}

export type SessionSumAggregateInputType = {
  attendanceCount?: true
  questionsCount?: true
}

export type SessionMinAggregateInputType = {
  id?: true
  sabaqId?: true
  scheduledAt?: true
  cutoffTime?: true
  startedAt?: true
  endedAt?: true
  isActive?: true
  isSynced?: true
  createdBy?: true
  createdAt?: true
  attendanceCount?: true
  questionsCount?: true
}

export type SessionMaxAggregateInputType = {
  id?: true
  sabaqId?: true
  scheduledAt?: true
  cutoffTime?: true
  startedAt?: true
  endedAt?: true
  isActive?: true
  isSynced?: true
  createdBy?: true
  createdAt?: true
  attendanceCount?: true
  questionsCount?: true
}

export type SessionCountAggregateInputType = {
  id?: true
  sabaqId?: true
  scheduledAt?: true
  cutoffTime?: true
  startedAt?: true
  endedAt?: true
  isActive?: true
  isSynced?: true
  createdBy?: true
  createdAt?: true
  attendanceCount?: true
  questionsCount?: true
  _all?: true
}

export type SessionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Session to aggregate.
   */
  where?: Prisma.SessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sessions to fetch.
   */
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Sessions
  **/
  _count?: true | SessionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SessionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SessionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SessionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SessionMaxAggregateInputType
}

export type GetSessionAggregateType<T extends SessionAggregateArgs> = {
      [P in keyof T & keyof AggregateSession]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSession[P]>
    : Prisma.GetScalarType<T[P], AggregateSession[P]>
}




export type SessionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SessionWhereInput
  orderBy?: Prisma.SessionOrderByWithAggregationInput | Prisma.SessionOrderByWithAggregationInput[]
  by: Prisma.SessionScalarFieldEnum[] | Prisma.SessionScalarFieldEnum
  having?: Prisma.SessionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SessionCountAggregateInputType | true
  _avg?: SessionAvgAggregateInputType
  _sum?: SessionSumAggregateInputType
  _min?: SessionMinAggregateInputType
  _max?: SessionMaxAggregateInputType
}

export type SessionGroupByOutputType = {
  id: string
  sabaqId: string
  scheduledAt: Date
  cutoffTime: Date
  startedAt: Date | null
  endedAt: Date | null
  isActive: boolean
  isSynced: boolean
  createdBy: string
  createdAt: Date
  attendanceCount: number
  questionsCount: number
  _count: SessionCountAggregateOutputType | null
  _avg: SessionAvgAggregateOutputType | null
  _sum: SessionSumAggregateOutputType | null
  _min: SessionMinAggregateOutputType | null
  _max: SessionMaxAggregateOutputType | null
}

type GetSessionGroupByPayload<T extends SessionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SessionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SessionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SessionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SessionGroupByOutputType[P]>
      }
    >
  >



export type SessionWhereInput = {
  AND?: Prisma.SessionWhereInput | Prisma.SessionWhereInput[]
  OR?: Prisma.SessionWhereInput[]
  NOT?: Prisma.SessionWhereInput | Prisma.SessionWhereInput[]
  id?: Prisma.StringFilter<"Session"> | string
  sabaqId?: Prisma.StringFilter<"Session"> | string
  scheduledAt?: Prisma.DateTimeFilter<"Session"> | Date | string
  cutoffTime?: Prisma.DateTimeFilter<"Session"> | Date | string
  startedAt?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  endedAt?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  isActive?: Prisma.BoolFilter<"Session"> | boolean
  isSynced?: Prisma.BoolFilter<"Session"> | boolean
  createdBy?: Prisma.StringFilter<"Session"> | string
  createdAt?: Prisma.DateTimeFilter<"Session"> | Date | string
  attendanceCount?: Prisma.IntFilter<"Session"> | number
  questionsCount?: Prisma.IntFilter<"Session"> | number
  sabaq?: Prisma.XOR<Prisma.SabaqScalarRelationFilter, Prisma.SabaqWhereInput>
  activeForSabaq?: Prisma.XOR<Prisma.SabaqNullableScalarRelationFilter, Prisma.SabaqWhereInput> | null
  attendances?: Prisma.AttendanceListRelationFilter
  questions?: Prisma.QuestionListRelationFilter
  feedback?: Prisma.FeedbackListRelationFilter
  attendanceRequests?: Prisma.AttendanceRequestListRelationFilter
}

export type SessionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  cutoffTime?: Prisma.SortOrder
  startedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isSynced?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  attendanceCount?: Prisma.SortOrder
  questionsCount?: Prisma.SortOrder
  sabaq?: Prisma.SabaqOrderByWithRelationInput
  activeForSabaq?: Prisma.SabaqOrderByWithRelationInput
  attendances?: Prisma.AttendanceOrderByRelationAggregateInput
  questions?: Prisma.QuestionOrderByRelationAggregateInput
  feedback?: Prisma.FeedbackOrderByRelationAggregateInput
  attendanceRequests?: Prisma.AttendanceRequestOrderByRelationAggregateInput
}

export type SessionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SessionWhereInput | Prisma.SessionWhereInput[]
  OR?: Prisma.SessionWhereInput[]
  NOT?: Prisma.SessionWhereInput | Prisma.SessionWhereInput[]
  sabaqId?: Prisma.StringFilter<"Session"> | string
  scheduledAt?: Prisma.DateTimeFilter<"Session"> | Date | string
  cutoffTime?: Prisma.DateTimeFilter<"Session"> | Date | string
  startedAt?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  endedAt?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  isActive?: Prisma.BoolFilter<"Session"> | boolean
  isSynced?: Prisma.BoolFilter<"Session"> | boolean
  createdBy?: Prisma.StringFilter<"Session"> | string
  createdAt?: Prisma.DateTimeFilter<"Session"> | Date | string
  attendanceCount?: Prisma.IntFilter<"Session"> | number
  questionsCount?: Prisma.IntFilter<"Session"> | number
  sabaq?: Prisma.XOR<Prisma.SabaqScalarRelationFilter, Prisma.SabaqWhereInput>
  activeForSabaq?: Prisma.XOR<Prisma.SabaqNullableScalarRelationFilter, Prisma.SabaqWhereInput> | null
  attendances?: Prisma.AttendanceListRelationFilter
  questions?: Prisma.QuestionListRelationFilter
  feedback?: Prisma.FeedbackListRelationFilter
  attendanceRequests?: Prisma.AttendanceRequestListRelationFilter
}, "id">

export type SessionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  cutoffTime?: Prisma.SortOrder
  startedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  endedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isSynced?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  attendanceCount?: Prisma.SortOrder
  questionsCount?: Prisma.SortOrder
  _count?: Prisma.SessionCountOrderByAggregateInput
  _avg?: Prisma.SessionAvgOrderByAggregateInput
  _max?: Prisma.SessionMaxOrderByAggregateInput
  _min?: Prisma.SessionMinOrderByAggregateInput
  _sum?: Prisma.SessionSumOrderByAggregateInput
}

export type SessionScalarWhereWithAggregatesInput = {
  AND?: Prisma.SessionScalarWhereWithAggregatesInput | Prisma.SessionScalarWhereWithAggregatesInput[]
  OR?: Prisma.SessionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SessionScalarWhereWithAggregatesInput | Prisma.SessionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Session"> | string
  sabaqId?: Prisma.StringWithAggregatesFilter<"Session"> | string
  scheduledAt?: Prisma.DateTimeWithAggregatesFilter<"Session"> | Date | string
  cutoffTime?: Prisma.DateTimeWithAggregatesFilter<"Session"> | Date | string
  startedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Session"> | Date | string | null
  endedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Session"> | Date | string | null
  isActive?: Prisma.BoolWithAggregatesFilter<"Session"> | boolean
  isSynced?: Prisma.BoolWithAggregatesFilter<"Session"> | boolean
  createdBy?: Prisma.StringWithAggregatesFilter<"Session"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Session"> | Date | string
  attendanceCount?: Prisma.IntWithAggregatesFilter<"Session"> | number
  questionsCount?: Prisma.IntWithAggregatesFilter<"Session"> | number
}

export type SessionCreateInput = {
  id?: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  sabaq: Prisma.SabaqCreateNestedOneWithoutSessionsInput
  activeForSabaq?: Prisma.SabaqCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateInput = {
  id?: string
  sabaqId: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  activeForSabaq?: Prisma.SabaqUncheckedCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceUncheckedCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackUncheckedCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  sabaq?: Prisma.SabaqUpdateOneRequiredWithoutSessionsNestedInput
  activeForSabaq?: Prisma.SabaqUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  activeForSabaq?: Prisma.SabaqUncheckedUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUncheckedUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUncheckedUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionCreateManyInput = {
  id?: string
  sabaqId: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
}

export type SessionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SessionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SessionScalarRelationFilter = {
  is?: Prisma.SessionWhereInput
  isNot?: Prisma.SessionWhereInput
}

export type SessionListRelationFilter = {
  every?: Prisma.SessionWhereInput
  some?: Prisma.SessionWhereInput
  none?: Prisma.SessionWhereInput
}

export type SessionNullableScalarRelationFilter = {
  is?: Prisma.SessionWhereInput | null
  isNot?: Prisma.SessionWhereInput | null
}

export type SessionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SessionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  cutoffTime?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isSynced?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  attendanceCount?: Prisma.SortOrder
  questionsCount?: Prisma.SortOrder
}

export type SessionAvgOrderByAggregateInput = {
  attendanceCount?: Prisma.SortOrder
  questionsCount?: Prisma.SortOrder
}

export type SessionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  cutoffTime?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isSynced?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  attendanceCount?: Prisma.SortOrder
  questionsCount?: Prisma.SortOrder
}

export type SessionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  sabaqId?: Prisma.SortOrder
  scheduledAt?: Prisma.SortOrder
  cutoffTime?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  endedAt?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  isSynced?: Prisma.SortOrder
  createdBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  attendanceCount?: Prisma.SortOrder
  questionsCount?: Prisma.SortOrder
}

export type SessionSumOrderByAggregateInput = {
  attendanceCount?: Prisma.SortOrder
  questionsCount?: Prisma.SortOrder
}

export type SessionCreateNestedOneWithoutFeedbackInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutFeedbackInput, Prisma.SessionUncheckedCreateWithoutFeedbackInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutFeedbackInput
  connect?: Prisma.SessionWhereUniqueInput
}

export type SessionUpdateOneRequiredWithoutFeedbackNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutFeedbackInput, Prisma.SessionUncheckedCreateWithoutFeedbackInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutFeedbackInput
  upsert?: Prisma.SessionUpsertWithoutFeedbackInput
  connect?: Prisma.SessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SessionUpdateToOneWithWhereWithoutFeedbackInput, Prisma.SessionUpdateWithoutFeedbackInput>, Prisma.SessionUncheckedUpdateWithoutFeedbackInput>
}

export type SessionCreateNestedManyWithoutSabaqInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSabaqInput, Prisma.SessionUncheckedCreateWithoutSabaqInput> | Prisma.SessionCreateWithoutSabaqInput[] | Prisma.SessionUncheckedCreateWithoutSabaqInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSabaqInput | Prisma.SessionCreateOrConnectWithoutSabaqInput[]
  createMany?: Prisma.SessionCreateManySabaqInputEnvelope
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
}

export type SessionCreateNestedOneWithoutActiveForSabaqInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutActiveForSabaqInput, Prisma.SessionUncheckedCreateWithoutActiveForSabaqInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutActiveForSabaqInput
  connect?: Prisma.SessionWhereUniqueInput
}

export type SessionUncheckedCreateNestedManyWithoutSabaqInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSabaqInput, Prisma.SessionUncheckedCreateWithoutSabaqInput> | Prisma.SessionCreateWithoutSabaqInput[] | Prisma.SessionUncheckedCreateWithoutSabaqInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSabaqInput | Prisma.SessionCreateOrConnectWithoutSabaqInput[]
  createMany?: Prisma.SessionCreateManySabaqInputEnvelope
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
}

export type SessionUpdateManyWithoutSabaqNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSabaqInput, Prisma.SessionUncheckedCreateWithoutSabaqInput> | Prisma.SessionCreateWithoutSabaqInput[] | Prisma.SessionUncheckedCreateWithoutSabaqInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSabaqInput | Prisma.SessionCreateOrConnectWithoutSabaqInput[]
  upsert?: Prisma.SessionUpsertWithWhereUniqueWithoutSabaqInput | Prisma.SessionUpsertWithWhereUniqueWithoutSabaqInput[]
  createMany?: Prisma.SessionCreateManySabaqInputEnvelope
  set?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  disconnect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  delete?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  update?: Prisma.SessionUpdateWithWhereUniqueWithoutSabaqInput | Prisma.SessionUpdateWithWhereUniqueWithoutSabaqInput[]
  updateMany?: Prisma.SessionUpdateManyWithWhereWithoutSabaqInput | Prisma.SessionUpdateManyWithWhereWithoutSabaqInput[]
  deleteMany?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
}

export type SessionUpdateOneWithoutActiveForSabaqNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutActiveForSabaqInput, Prisma.SessionUncheckedCreateWithoutActiveForSabaqInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutActiveForSabaqInput
  upsert?: Prisma.SessionUpsertWithoutActiveForSabaqInput
  disconnect?: Prisma.SessionWhereInput | boolean
  delete?: Prisma.SessionWhereInput | boolean
  connect?: Prisma.SessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SessionUpdateToOneWithWhereWithoutActiveForSabaqInput, Prisma.SessionUpdateWithoutActiveForSabaqInput>, Prisma.SessionUncheckedUpdateWithoutActiveForSabaqInput>
}

export type SessionUncheckedUpdateManyWithoutSabaqNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutSabaqInput, Prisma.SessionUncheckedCreateWithoutSabaqInput> | Prisma.SessionCreateWithoutSabaqInput[] | Prisma.SessionUncheckedCreateWithoutSabaqInput[]
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutSabaqInput | Prisma.SessionCreateOrConnectWithoutSabaqInput[]
  upsert?: Prisma.SessionUpsertWithWhereUniqueWithoutSabaqInput | Prisma.SessionUpsertWithWhereUniqueWithoutSabaqInput[]
  createMany?: Prisma.SessionCreateManySabaqInputEnvelope
  set?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  disconnect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  delete?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  connect?: Prisma.SessionWhereUniqueInput | Prisma.SessionWhereUniqueInput[]
  update?: Prisma.SessionUpdateWithWhereUniqueWithoutSabaqInput | Prisma.SessionUpdateWithWhereUniqueWithoutSabaqInput[]
  updateMany?: Prisma.SessionUpdateManyWithWhereWithoutSabaqInput | Prisma.SessionUpdateManyWithWhereWithoutSabaqInput[]
  deleteMany?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
}

export type SessionCreateNestedOneWithoutAttendancesInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutAttendancesInput, Prisma.SessionUncheckedCreateWithoutAttendancesInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutAttendancesInput
  connect?: Prisma.SessionWhereUniqueInput
}

export type SessionUpdateOneRequiredWithoutAttendancesNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutAttendancesInput, Prisma.SessionUncheckedCreateWithoutAttendancesInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutAttendancesInput
  upsert?: Prisma.SessionUpsertWithoutAttendancesInput
  connect?: Prisma.SessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SessionUpdateToOneWithWhereWithoutAttendancesInput, Prisma.SessionUpdateWithoutAttendancesInput>, Prisma.SessionUncheckedUpdateWithoutAttendancesInput>
}

export type SessionCreateNestedOneWithoutQuestionsInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutQuestionsInput, Prisma.SessionUncheckedCreateWithoutQuestionsInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutQuestionsInput
  connect?: Prisma.SessionWhereUniqueInput
}

export type SessionUpdateOneRequiredWithoutQuestionsNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutQuestionsInput, Prisma.SessionUncheckedCreateWithoutQuestionsInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutQuestionsInput
  upsert?: Prisma.SessionUpsertWithoutQuestionsInput
  connect?: Prisma.SessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SessionUpdateToOneWithWhereWithoutQuestionsInput, Prisma.SessionUpdateWithoutQuestionsInput>, Prisma.SessionUncheckedUpdateWithoutQuestionsInput>
}

export type SessionCreateNestedOneWithoutAttendanceRequestsInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutAttendanceRequestsInput, Prisma.SessionUncheckedCreateWithoutAttendanceRequestsInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutAttendanceRequestsInput
  connect?: Prisma.SessionWhereUniqueInput
}

export type SessionUpdateOneRequiredWithoutAttendanceRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.SessionCreateWithoutAttendanceRequestsInput, Prisma.SessionUncheckedCreateWithoutAttendanceRequestsInput>
  connectOrCreate?: Prisma.SessionCreateOrConnectWithoutAttendanceRequestsInput
  upsert?: Prisma.SessionUpsertWithoutAttendanceRequestsInput
  connect?: Prisma.SessionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SessionUpdateToOneWithWhereWithoutAttendanceRequestsInput, Prisma.SessionUpdateWithoutAttendanceRequestsInput>, Prisma.SessionUncheckedUpdateWithoutAttendanceRequestsInput>
}

export type SessionCreateWithoutFeedbackInput = {
  id?: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  sabaq: Prisma.SabaqCreateNestedOneWithoutSessionsInput
  activeForSabaq?: Prisma.SabaqCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateWithoutFeedbackInput = {
  id?: string
  sabaqId: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  activeForSabaq?: Prisma.SabaqUncheckedCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceUncheckedCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionCreateOrConnectWithoutFeedbackInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutFeedbackInput, Prisma.SessionUncheckedCreateWithoutFeedbackInput>
}

export type SessionUpsertWithoutFeedbackInput = {
  update: Prisma.XOR<Prisma.SessionUpdateWithoutFeedbackInput, Prisma.SessionUncheckedUpdateWithoutFeedbackInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutFeedbackInput, Prisma.SessionUncheckedCreateWithoutFeedbackInput>
  where?: Prisma.SessionWhereInput
}

export type SessionUpdateToOneWithWhereWithoutFeedbackInput = {
  where?: Prisma.SessionWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutFeedbackInput, Prisma.SessionUncheckedUpdateWithoutFeedbackInput>
}

export type SessionUpdateWithoutFeedbackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  sabaq?: Prisma.SabaqUpdateOneRequiredWithoutSessionsNestedInput
  activeForSabaq?: Prisma.SabaqUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateWithoutFeedbackInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  activeForSabaq?: Prisma.SabaqUncheckedUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUncheckedUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionCreateWithoutSabaqInput = {
  id?: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  activeForSabaq?: Prisma.SabaqCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateWithoutSabaqInput = {
  id?: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  activeForSabaq?: Prisma.SabaqUncheckedCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceUncheckedCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackUncheckedCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionCreateOrConnectWithoutSabaqInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutSabaqInput, Prisma.SessionUncheckedCreateWithoutSabaqInput>
}

export type SessionCreateManySabaqInputEnvelope = {
  data: Prisma.SessionCreateManySabaqInput | Prisma.SessionCreateManySabaqInput[]
  skipDuplicates?: boolean
}

export type SessionCreateWithoutActiveForSabaqInput = {
  id?: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  sabaq: Prisma.SabaqCreateNestedOneWithoutSessionsInput
  attendances?: Prisma.AttendanceCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateWithoutActiveForSabaqInput = {
  id?: string
  sabaqId: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  attendances?: Prisma.AttendanceUncheckedCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackUncheckedCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionCreateOrConnectWithoutActiveForSabaqInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutActiveForSabaqInput, Prisma.SessionUncheckedCreateWithoutActiveForSabaqInput>
}

export type SessionUpsertWithWhereUniqueWithoutSabaqInput = {
  where: Prisma.SessionWhereUniqueInput
  update: Prisma.XOR<Prisma.SessionUpdateWithoutSabaqInput, Prisma.SessionUncheckedUpdateWithoutSabaqInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutSabaqInput, Prisma.SessionUncheckedCreateWithoutSabaqInput>
}

export type SessionUpdateWithWhereUniqueWithoutSabaqInput = {
  where: Prisma.SessionWhereUniqueInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutSabaqInput, Prisma.SessionUncheckedUpdateWithoutSabaqInput>
}

export type SessionUpdateManyWithWhereWithoutSabaqInput = {
  where: Prisma.SessionScalarWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateManyMutationInput, Prisma.SessionUncheckedUpdateManyWithoutSabaqInput>
}

export type SessionScalarWhereInput = {
  AND?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
  OR?: Prisma.SessionScalarWhereInput[]
  NOT?: Prisma.SessionScalarWhereInput | Prisma.SessionScalarWhereInput[]
  id?: Prisma.StringFilter<"Session"> | string
  sabaqId?: Prisma.StringFilter<"Session"> | string
  scheduledAt?: Prisma.DateTimeFilter<"Session"> | Date | string
  cutoffTime?: Prisma.DateTimeFilter<"Session"> | Date | string
  startedAt?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  endedAt?: Prisma.DateTimeNullableFilter<"Session"> | Date | string | null
  isActive?: Prisma.BoolFilter<"Session"> | boolean
  isSynced?: Prisma.BoolFilter<"Session"> | boolean
  createdBy?: Prisma.StringFilter<"Session"> | string
  createdAt?: Prisma.DateTimeFilter<"Session"> | Date | string
  attendanceCount?: Prisma.IntFilter<"Session"> | number
  questionsCount?: Prisma.IntFilter<"Session"> | number
}

export type SessionUpsertWithoutActiveForSabaqInput = {
  update: Prisma.XOR<Prisma.SessionUpdateWithoutActiveForSabaqInput, Prisma.SessionUncheckedUpdateWithoutActiveForSabaqInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutActiveForSabaqInput, Prisma.SessionUncheckedCreateWithoutActiveForSabaqInput>
  where?: Prisma.SessionWhereInput
}

export type SessionUpdateToOneWithWhereWithoutActiveForSabaqInput = {
  where?: Prisma.SessionWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutActiveForSabaqInput, Prisma.SessionUncheckedUpdateWithoutActiveForSabaqInput>
}

export type SessionUpdateWithoutActiveForSabaqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  sabaq?: Prisma.SabaqUpdateOneRequiredWithoutSessionsNestedInput
  attendances?: Prisma.AttendanceUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateWithoutActiveForSabaqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  attendances?: Prisma.AttendanceUncheckedUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUncheckedUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionCreateWithoutAttendancesInput = {
  id?: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  sabaq: Prisma.SabaqCreateNestedOneWithoutSessionsInput
  activeForSabaq?: Prisma.SabaqCreateNestedOneWithoutActiveSessionInput
  questions?: Prisma.QuestionCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateWithoutAttendancesInput = {
  id?: string
  sabaqId: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  activeForSabaq?: Prisma.SabaqUncheckedCreateNestedOneWithoutActiveSessionInput
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackUncheckedCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionCreateOrConnectWithoutAttendancesInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutAttendancesInput, Prisma.SessionUncheckedCreateWithoutAttendancesInput>
}

export type SessionUpsertWithoutAttendancesInput = {
  update: Prisma.XOR<Prisma.SessionUpdateWithoutAttendancesInput, Prisma.SessionUncheckedUpdateWithoutAttendancesInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutAttendancesInput, Prisma.SessionUncheckedCreateWithoutAttendancesInput>
  where?: Prisma.SessionWhereInput
}

export type SessionUpdateToOneWithWhereWithoutAttendancesInput = {
  where?: Prisma.SessionWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutAttendancesInput, Prisma.SessionUncheckedUpdateWithoutAttendancesInput>
}

export type SessionUpdateWithoutAttendancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  sabaq?: Prisma.SabaqUpdateOneRequiredWithoutSessionsNestedInput
  activeForSabaq?: Prisma.SabaqUpdateOneWithoutActiveSessionNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateWithoutAttendancesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  activeForSabaq?: Prisma.SabaqUncheckedUpdateOneWithoutActiveSessionNestedInput
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUncheckedUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionCreateWithoutQuestionsInput = {
  id?: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  sabaq: Prisma.SabaqCreateNestedOneWithoutSessionsInput
  activeForSabaq?: Prisma.SabaqCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateWithoutQuestionsInput = {
  id?: string
  sabaqId: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  activeForSabaq?: Prisma.SabaqUncheckedCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceUncheckedCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackUncheckedCreateNestedManyWithoutSessionInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionCreateOrConnectWithoutQuestionsInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutQuestionsInput, Prisma.SessionUncheckedCreateWithoutQuestionsInput>
}

export type SessionUpsertWithoutQuestionsInput = {
  update: Prisma.XOR<Prisma.SessionUpdateWithoutQuestionsInput, Prisma.SessionUncheckedUpdateWithoutQuestionsInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutQuestionsInput, Prisma.SessionUncheckedCreateWithoutQuestionsInput>
  where?: Prisma.SessionWhereInput
}

export type SessionUpdateToOneWithWhereWithoutQuestionsInput = {
  where?: Prisma.SessionWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutQuestionsInput, Prisma.SessionUncheckedUpdateWithoutQuestionsInput>
}

export type SessionUpdateWithoutQuestionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  sabaq?: Prisma.SabaqUpdateOneRequiredWithoutSessionsNestedInput
  activeForSabaq?: Prisma.SabaqUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateWithoutQuestionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  activeForSabaq?: Prisma.SabaqUncheckedUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUncheckedUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUncheckedUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionCreateWithoutAttendanceRequestsInput = {
  id?: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  sabaq: Prisma.SabaqCreateNestedOneWithoutSessionsInput
  activeForSabaq?: Prisma.SabaqCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackCreateNestedManyWithoutSessionInput
}

export type SessionUncheckedCreateWithoutAttendanceRequestsInput = {
  id?: string
  sabaqId: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
  activeForSabaq?: Prisma.SabaqUncheckedCreateNestedOneWithoutActiveSessionInput
  attendances?: Prisma.AttendanceUncheckedCreateNestedManyWithoutSessionInput
  questions?: Prisma.QuestionUncheckedCreateNestedManyWithoutSessionInput
  feedback?: Prisma.FeedbackUncheckedCreateNestedManyWithoutSessionInput
}

export type SessionCreateOrConnectWithoutAttendanceRequestsInput = {
  where: Prisma.SessionWhereUniqueInput
  create: Prisma.XOR<Prisma.SessionCreateWithoutAttendanceRequestsInput, Prisma.SessionUncheckedCreateWithoutAttendanceRequestsInput>
}

export type SessionUpsertWithoutAttendanceRequestsInput = {
  update: Prisma.XOR<Prisma.SessionUpdateWithoutAttendanceRequestsInput, Prisma.SessionUncheckedUpdateWithoutAttendanceRequestsInput>
  create: Prisma.XOR<Prisma.SessionCreateWithoutAttendanceRequestsInput, Prisma.SessionUncheckedCreateWithoutAttendanceRequestsInput>
  where?: Prisma.SessionWhereInput
}

export type SessionUpdateToOneWithWhereWithoutAttendanceRequestsInput = {
  where?: Prisma.SessionWhereInput
  data: Prisma.XOR<Prisma.SessionUpdateWithoutAttendanceRequestsInput, Prisma.SessionUncheckedUpdateWithoutAttendanceRequestsInput>
}

export type SessionUpdateWithoutAttendanceRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  sabaq?: Prisma.SabaqUpdateOneRequiredWithoutSessionsNestedInput
  activeForSabaq?: Prisma.SabaqUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateWithoutAttendanceRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  sabaqId?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  activeForSabaq?: Prisma.SabaqUncheckedUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUncheckedUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionCreateManySabaqInput = {
  id?: string
  scheduledAt: Date | string
  cutoffTime: Date | string
  startedAt?: Date | string | null
  endedAt?: Date | string | null
  isActive?: boolean
  isSynced?: boolean
  createdBy: string
  createdAt?: Date | string
  attendanceCount?: number
  questionsCount?: number
}

export type SessionUpdateWithoutSabaqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  activeForSabaq?: Prisma.SabaqUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateWithoutSabaqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  activeForSabaq?: Prisma.SabaqUncheckedUpdateOneWithoutActiveSessionNestedInput
  attendances?: Prisma.AttendanceUncheckedUpdateManyWithoutSessionNestedInput
  questions?: Prisma.QuestionUncheckedUpdateManyWithoutSessionNestedInput
  feedback?: Prisma.FeedbackUncheckedUpdateManyWithoutSessionNestedInput
  attendanceRequests?: Prisma.AttendanceRequestUncheckedUpdateManyWithoutSessionNestedInput
}

export type SessionUncheckedUpdateManyWithoutSabaqInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  scheduledAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cutoffTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  endedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  attendanceCount?: Prisma.IntFieldUpdateOperationsInput | number
  questionsCount?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type SessionCountOutputType
 */

export type SessionCountOutputType = {
  attendances: number
  questions: number
  feedback: number
  attendanceRequests: number
}

export type SessionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  attendances?: boolean | SessionCountOutputTypeCountAttendancesArgs
  questions?: boolean | SessionCountOutputTypeCountQuestionsArgs
  feedback?: boolean | SessionCountOutputTypeCountFeedbackArgs
  attendanceRequests?: boolean | SessionCountOutputTypeCountAttendanceRequestsArgs
}

/**
 * SessionCountOutputType without action
 */
export type SessionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SessionCountOutputType
   */
  select?: Prisma.SessionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SessionCountOutputType without action
 */
export type SessionCountOutputTypeCountAttendancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttendanceWhereInput
}

/**
 * SessionCountOutputType without action
 */
export type SessionCountOutputTypeCountQuestionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.QuestionWhereInput
}

/**
 * SessionCountOutputType without action
 */
export type SessionCountOutputTypeCountFeedbackArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FeedbackWhereInput
}

/**
 * SessionCountOutputType without action
 */
export type SessionCountOutputTypeCountAttendanceRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AttendanceRequestWhereInput
}


export type SessionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sabaqId?: boolean
  scheduledAt?: boolean
  cutoffTime?: boolean
  startedAt?: boolean
  endedAt?: boolean
  isActive?: boolean
  isSynced?: boolean
  createdBy?: boolean
  createdAt?: boolean
  attendanceCount?: boolean
  questionsCount?: boolean
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
  activeForSabaq?: boolean | Prisma.Session$activeForSabaqArgs<ExtArgs>
  attendances?: boolean | Prisma.Session$attendancesArgs<ExtArgs>
  questions?: boolean | Prisma.Session$questionsArgs<ExtArgs>
  feedback?: boolean | Prisma.Session$feedbackArgs<ExtArgs>
  attendanceRequests?: boolean | Prisma.Session$attendanceRequestsArgs<ExtArgs>
  _count?: boolean | Prisma.SessionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["session"]>

export type SessionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sabaqId?: boolean
  scheduledAt?: boolean
  cutoffTime?: boolean
  startedAt?: boolean
  endedAt?: boolean
  isActive?: boolean
  isSynced?: boolean
  createdBy?: boolean
  createdAt?: boolean
  attendanceCount?: boolean
  questionsCount?: boolean
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
}, ExtArgs["result"]["session"]>

export type SessionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  sabaqId?: boolean
  scheduledAt?: boolean
  cutoffTime?: boolean
  startedAt?: boolean
  endedAt?: boolean
  isActive?: boolean
  isSynced?: boolean
  createdBy?: boolean
  createdAt?: boolean
  attendanceCount?: boolean
  questionsCount?: boolean
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
}, ExtArgs["result"]["session"]>

export type SessionSelectScalar = {
  id?: boolean
  sabaqId?: boolean
  scheduledAt?: boolean
  cutoffTime?: boolean
  startedAt?: boolean
  endedAt?: boolean
  isActive?: boolean
  isSynced?: boolean
  createdBy?: boolean
  createdAt?: boolean
  attendanceCount?: boolean
  questionsCount?: boolean
}

export type SessionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "sabaqId" | "scheduledAt" | "cutoffTime" | "startedAt" | "endedAt" | "isActive" | "isSynced" | "createdBy" | "createdAt" | "attendanceCount" | "questionsCount", ExtArgs["result"]["session"]>
export type SessionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
  activeForSabaq?: boolean | Prisma.Session$activeForSabaqArgs<ExtArgs>
  attendances?: boolean | Prisma.Session$attendancesArgs<ExtArgs>
  questions?: boolean | Prisma.Session$questionsArgs<ExtArgs>
  feedback?: boolean | Prisma.Session$feedbackArgs<ExtArgs>
  attendanceRequests?: boolean | Prisma.Session$attendanceRequestsArgs<ExtArgs>
  _count?: boolean | Prisma.SessionCountOutputTypeDefaultArgs<ExtArgs>
}
export type SessionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
}
export type SessionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  sabaq?: boolean | Prisma.SabaqDefaultArgs<ExtArgs>
}

export type $SessionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Session"
  objects: {
    sabaq: Prisma.$SabaqPayload<ExtArgs>
    activeForSabaq: Prisma.$SabaqPayload<ExtArgs> | null
    attendances: Prisma.$AttendancePayload<ExtArgs>[]
    questions: Prisma.$QuestionPayload<ExtArgs>[]
    feedback: Prisma.$FeedbackPayload<ExtArgs>[]
    attendanceRequests: Prisma.$AttendanceRequestPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    sabaqId: string
    scheduledAt: Date
    cutoffTime: Date
    startedAt: Date | null
    endedAt: Date | null
    isActive: boolean
    isSynced: boolean
    createdBy: string
    createdAt: Date
    attendanceCount: number
    questionsCount: number
  }, ExtArgs["result"]["session"]>
  composites: {}
}

export type SessionGetPayload<S extends boolean | null | undefined | SessionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SessionPayload, S>

export type SessionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SessionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SessionCountAggregateInputType | true
  }

export interface SessionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Session'], meta: { name: 'Session' } }
  /**
   * Find zero or one Session that matches the filter.
   * @param {SessionFindUniqueArgs} args - Arguments to find a Session
   * @example
   * // Get one Session
   * const session = await prisma.session.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SessionFindUniqueArgs>(args: Prisma.SelectSubset<T, SessionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Session that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SessionFindUniqueOrThrowArgs} args - Arguments to find a Session
   * @example
   * // Get one Session
   * const session = await prisma.session.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SessionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SessionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Session that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionFindFirstArgs} args - Arguments to find a Session
   * @example
   * // Get one Session
   * const session = await prisma.session.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SessionFindFirstArgs>(args?: Prisma.SelectSubset<T, SessionFindFirstArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Session that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionFindFirstOrThrowArgs} args - Arguments to find a Session
   * @example
   * // Get one Session
   * const session = await prisma.session.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SessionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SessionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Sessions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Sessions
   * const sessions = await prisma.session.findMany()
   * 
   * // Get first 10 Sessions
   * const sessions = await prisma.session.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sessionWithIdOnly = await prisma.session.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SessionFindManyArgs>(args?: Prisma.SelectSubset<T, SessionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Session.
   * @param {SessionCreateArgs} args - Arguments to create a Session.
   * @example
   * // Create one Session
   * const Session = await prisma.session.create({
   *   data: {
   *     // ... data to create a Session
   *   }
   * })
   * 
   */
  create<T extends SessionCreateArgs>(args: Prisma.SelectSubset<T, SessionCreateArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Sessions.
   * @param {SessionCreateManyArgs} args - Arguments to create many Sessions.
   * @example
   * // Create many Sessions
   * const session = await prisma.session.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SessionCreateManyArgs>(args?: Prisma.SelectSubset<T, SessionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Sessions and returns the data saved in the database.
   * @param {SessionCreateManyAndReturnArgs} args - Arguments to create many Sessions.
   * @example
   * // Create many Sessions
   * const session = await prisma.session.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Sessions and only return the `id`
   * const sessionWithIdOnly = await prisma.session.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SessionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SessionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Session.
   * @param {SessionDeleteArgs} args - Arguments to delete one Session.
   * @example
   * // Delete one Session
   * const Session = await prisma.session.delete({
   *   where: {
   *     // ... filter to delete one Session
   *   }
   * })
   * 
   */
  delete<T extends SessionDeleteArgs>(args: Prisma.SelectSubset<T, SessionDeleteArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Session.
   * @param {SessionUpdateArgs} args - Arguments to update one Session.
   * @example
   * // Update one Session
   * const session = await prisma.session.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SessionUpdateArgs>(args: Prisma.SelectSubset<T, SessionUpdateArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Sessions.
   * @param {SessionDeleteManyArgs} args - Arguments to filter Sessions to delete.
   * @example
   * // Delete a few Sessions
   * const { count } = await prisma.session.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SessionDeleteManyArgs>(args?: Prisma.SelectSubset<T, SessionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Sessions
   * const session = await prisma.session.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SessionUpdateManyArgs>(args: Prisma.SelectSubset<T, SessionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Sessions and returns the data updated in the database.
   * @param {SessionUpdateManyAndReturnArgs} args - Arguments to update many Sessions.
   * @example
   * // Update many Sessions
   * const session = await prisma.session.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Sessions and only return the `id`
   * const sessionWithIdOnly = await prisma.session.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SessionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SessionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Session.
   * @param {SessionUpsertArgs} args - Arguments to update or create a Session.
   * @example
   * // Update or create a Session
   * const session = await prisma.session.upsert({
   *   create: {
   *     // ... data to create a Session
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Session we want to update
   *   }
   * })
   */
  upsert<T extends SessionUpsertArgs>(args: Prisma.SelectSubset<T, SessionUpsertArgs<ExtArgs>>): Prisma.Prisma__SessionClient<runtime.Types.Result.GetResult<Prisma.$SessionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Sessions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionCountArgs} args - Arguments to filter Sessions to count.
   * @example
   * // Count the number of Sessions
   * const count = await prisma.session.count({
   *   where: {
   *     // ... the filter for the Sessions we want to count
   *   }
   * })
  **/
  count<T extends SessionCountArgs>(
    args?: Prisma.Subset<T, SessionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SessionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SessionAggregateArgs>(args: Prisma.Subset<T, SessionAggregateArgs>): Prisma.PrismaPromise<GetSessionAggregateType<T>>

  /**
   * Group by Session.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SessionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SessionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SessionGroupByArgs['orderBy'] }
      : { orderBy?: SessionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SessionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSessionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Session model
 */
readonly fields: SessionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Session.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SessionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  sabaq<T extends Prisma.SabaqDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SabaqDefaultArgs<ExtArgs>>): Prisma.Prisma__SabaqClient<runtime.Types.Result.GetResult<Prisma.$SabaqPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  activeForSabaq<T extends Prisma.Session$activeForSabaqArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Session$activeForSabaqArgs<ExtArgs>>): Prisma.Prisma__SabaqClient<runtime.Types.Result.GetResult<Prisma.$SabaqPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  attendances<T extends Prisma.Session$attendancesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Session$attendancesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttendancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  questions<T extends Prisma.Session$questionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Session$questionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$QuestionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  feedback<T extends Prisma.Session$feedbackArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Session$feedbackArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FeedbackPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  attendanceRequests<T extends Prisma.Session$attendanceRequestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Session$attendanceRequestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AttendanceRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Session model
 */
export interface SessionFieldRefs {
  readonly id: Prisma.FieldRef<"Session", 'String'>
  readonly sabaqId: Prisma.FieldRef<"Session", 'String'>
  readonly scheduledAt: Prisma.FieldRef<"Session", 'DateTime'>
  readonly cutoffTime: Prisma.FieldRef<"Session", 'DateTime'>
  readonly startedAt: Prisma.FieldRef<"Session", 'DateTime'>
  readonly endedAt: Prisma.FieldRef<"Session", 'DateTime'>
  readonly isActive: Prisma.FieldRef<"Session", 'Boolean'>
  readonly isSynced: Prisma.FieldRef<"Session", 'Boolean'>
  readonly createdBy: Prisma.FieldRef<"Session", 'String'>
  readonly createdAt: Prisma.FieldRef<"Session", 'DateTime'>
  readonly attendanceCount: Prisma.FieldRef<"Session", 'Int'>
  readonly questionsCount: Prisma.FieldRef<"Session", 'Int'>
}
    

// Custom InputTypes
/**
 * Session findUnique
 */
export type SessionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Session to fetch.
   */
  where: Prisma.SessionWhereUniqueInput
}

/**
 * Session findUniqueOrThrow
 */
export type SessionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Session to fetch.
   */
  where: Prisma.SessionWhereUniqueInput
}

/**
 * Session findFirst
 */
export type SessionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Session to fetch.
   */
  where?: Prisma.SessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sessions to fetch.
   */
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sessions.
   */
  cursor?: Prisma.SessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sessions.
   */
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * Session findFirstOrThrow
 */
export type SessionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Session to fetch.
   */
  where?: Prisma.SessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sessions to fetch.
   */
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Sessions.
   */
  cursor?: Prisma.SessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sessions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Sessions.
   */
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * Session findMany
 */
export type SessionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter, which Sessions to fetch.
   */
  where?: Prisma.SessionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Sessions to fetch.
   */
  orderBy?: Prisma.SessionOrderByWithRelationInput | Prisma.SessionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Sessions.
   */
  cursor?: Prisma.SessionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Sessions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Sessions.
   */
  skip?: number
  distinct?: Prisma.SessionScalarFieldEnum | Prisma.SessionScalarFieldEnum[]
}

/**
 * Session create
 */
export type SessionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * The data needed to create a Session.
   */
  data: Prisma.XOR<Prisma.SessionCreateInput, Prisma.SessionUncheckedCreateInput>
}

/**
 * Session createMany
 */
export type SessionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Sessions.
   */
  data: Prisma.SessionCreateManyInput | Prisma.SessionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Session createManyAndReturn
 */
export type SessionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * The data used to create many Sessions.
   */
  data: Prisma.SessionCreateManyInput | Prisma.SessionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Session update
 */
export type SessionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * The data needed to update a Session.
   */
  data: Prisma.XOR<Prisma.SessionUpdateInput, Prisma.SessionUncheckedUpdateInput>
  /**
   * Choose, which Session to update.
   */
  where: Prisma.SessionWhereUniqueInput
}

/**
 * Session updateMany
 */
export type SessionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Sessions.
   */
  data: Prisma.XOR<Prisma.SessionUpdateManyMutationInput, Prisma.SessionUncheckedUpdateManyInput>
  /**
   * Filter which Sessions to update
   */
  where?: Prisma.SessionWhereInput
  /**
   * Limit how many Sessions to update.
   */
  limit?: number
}

/**
 * Session updateManyAndReturn
 */
export type SessionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * The data used to update Sessions.
   */
  data: Prisma.XOR<Prisma.SessionUpdateManyMutationInput, Prisma.SessionUncheckedUpdateManyInput>
  /**
   * Filter which Sessions to update
   */
  where?: Prisma.SessionWhereInput
  /**
   * Limit how many Sessions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Session upsert
 */
export type SessionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * The filter to search for the Session to update in case it exists.
   */
  where: Prisma.SessionWhereUniqueInput
  /**
   * In case the Session found by the `where` argument doesn't exist, create a new Session with this data.
   */
  create: Prisma.XOR<Prisma.SessionCreateInput, Prisma.SessionUncheckedCreateInput>
  /**
   * In case the Session was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SessionUpdateInput, Prisma.SessionUncheckedUpdateInput>
}

/**
 * Session delete
 */
export type SessionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
  /**
   * Filter which Session to delete.
   */
  where: Prisma.SessionWhereUniqueInput
}

/**
 * Session deleteMany
 */
export type SessionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Sessions to delete
   */
  where?: Prisma.SessionWhereInput
  /**
   * Limit how many Sessions to delete.
   */
  limit?: number
}

/**
 * Session.activeForSabaq
 */
export type Session$activeForSabaqArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sabaq
   */
  select?: Prisma.SabaqSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sabaq
   */
  omit?: Prisma.SabaqOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SabaqInclude<ExtArgs> | null
  where?: Prisma.SabaqWhereInput
}

/**
 * Session.attendances
 */
export type Session$attendancesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Attendance
   */
  select?: Prisma.AttendanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Attendance
   */
  omit?: Prisma.AttendanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttendanceInclude<ExtArgs> | null
  where?: Prisma.AttendanceWhereInput
  orderBy?: Prisma.AttendanceOrderByWithRelationInput | Prisma.AttendanceOrderByWithRelationInput[]
  cursor?: Prisma.AttendanceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AttendanceScalarFieldEnum | Prisma.AttendanceScalarFieldEnum[]
}

/**
 * Session.questions
 */
export type Session$questionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Question
   */
  select?: Prisma.QuestionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Question
   */
  omit?: Prisma.QuestionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionInclude<ExtArgs> | null
  where?: Prisma.QuestionWhereInput
  orderBy?: Prisma.QuestionOrderByWithRelationInput | Prisma.QuestionOrderByWithRelationInput[]
  cursor?: Prisma.QuestionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.QuestionScalarFieldEnum | Prisma.QuestionScalarFieldEnum[]
}

/**
 * Session.feedback
 */
export type Session$feedbackArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Feedback
   */
  select?: Prisma.FeedbackSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Feedback
   */
  omit?: Prisma.FeedbackOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FeedbackInclude<ExtArgs> | null
  where?: Prisma.FeedbackWhereInput
  orderBy?: Prisma.FeedbackOrderByWithRelationInput | Prisma.FeedbackOrderByWithRelationInput[]
  cursor?: Prisma.FeedbackWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FeedbackScalarFieldEnum | Prisma.FeedbackScalarFieldEnum[]
}

/**
 * Session.attendanceRequests
 */
export type Session$attendanceRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AttendanceRequest
   */
  select?: Prisma.AttendanceRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AttendanceRequest
   */
  omit?: Prisma.AttendanceRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AttendanceRequestInclude<ExtArgs> | null
  where?: Prisma.AttendanceRequestWhereInput
  orderBy?: Prisma.AttendanceRequestOrderByWithRelationInput | Prisma.AttendanceRequestOrderByWithRelationInput[]
  cursor?: Prisma.AttendanceRequestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AttendanceRequestScalarFieldEnum | Prisma.AttendanceRequestScalarFieldEnum[]
}

/**
 * Session without action
 */
export type SessionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Session
   */
  select?: Prisma.SessionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Session
   */
  omit?: Prisma.SessionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SessionInclude<ExtArgs> | null
}
